version: "3.7"
services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9091"
    ports:
      - "9091:9091"
      - "9090:9090"
    environment:
      "MINIO_ROOT_USER": "root"
      "MINIO_ROOT_PASSWORD": "123456"
    volumes:
      - "./minio/data:/data"
