// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/generate_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleCategory int32

const (
	RuleCategory_RULE_CATEGORY_UNSPECIFIED RuleCategory = 0
	RuleCategory_RULE_CATEGORY_PERSONAL    RuleCategory = 1
	RuleCategory_RULE_CATEGORY_PRODUCT     RuleCategory = 2
	RuleCategory_RULE_CATEGORY_COMMERCE    RuleCategory = 3
	RuleCategory_RULE_CATEGORY_COMMON      RuleCategory = 4
	RuleCategory_RULE_CATEGORY_POSITION    RuleCategory = 5
	RuleCategory_RULE_CATEGORY_CUSTOM      RuleCategory = 6
)

// Enum value maps for RuleCategory.
var (
	RuleCategory_name = map[int32]string{
		0: "RULE_CATEGORY_UNSPECIFIED",
		1: "RULE_CATEGORY_PERSONAL",
		2: "RULE_CATEGORY_PRODUCT",
		3: "RULE_CATEGORY_COMMERCE",
		4: "RULE_CATEGORY_COMMON",
		5: "RULE_CATEGORY_POSITION",
		6: "RULE_CATEGORY_CUSTOM",
	}
	RuleCategory_value = map[string]int32{
		"RULE_CATEGORY_UNSPECIFIED": 0,
		"RULE_CATEGORY_PERSONAL":    1,
		"RULE_CATEGORY_PRODUCT":     2,
		"RULE_CATEGORY_COMMERCE":    3,
		"RULE_CATEGORY_COMMON":      4,
		"RULE_CATEGORY_POSITION":    5,
		"RULE_CATEGORY_CUSTOM":      6,
	}
)

func (x RuleCategory) Enum() *RuleCategory {
	p := new(RuleCategory)
	*p = x
	return p
}

func (x RuleCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_generate_service_proto_enumTypes[0].Descriptor()
}

func (RuleCategory) Type() protoreflect.EnumType {
	return &file_v1_generate_service_proto_enumTypes[0]
}

func (x RuleCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleCategory.Descriptor instead.
func (RuleCategory) EnumDescriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{0}
}

type GenerateAlgorithm int32

const (
	GenerateAlgorithm_GENERATE_ALGORITHM_UNSPECIFIED GenerateAlgorithm = 0
	GenerateAlgorithm_GENERATE_ALGORITHM_TIME        GenerateAlgorithm = 1
	GenerateAlgorithm_GENERATE_ALGORITHM_TIME_DATE   GenerateAlgorithm = 2
	GenerateAlgorithm_GENERATE_ALGORITHM_DEPARTMENT  GenerateAlgorithm = 3
	GenerateAlgorithm_GENERATE_ALGORITHM_COMPANY     GenerateAlgorithm = 4
	GenerateAlgorithm_GENERATE_ALGORITHM_SCRIPT      GenerateAlgorithm = 5
)

// Enum value maps for GenerateAlgorithm.
var (
	GenerateAlgorithm_name = map[int32]string{
		0: "GENERATE_ALGORITHM_UNSPECIFIED",
		1: "GENERATE_ALGORITHM_TIME",
		2: "GENERATE_ALGORITHM_TIME_DATE",
		3: "GENERATE_ALGORITHM_DEPARTMENT",
		4: "GENERATE_ALGORITHM_COMPANY",
		5: "GENERATE_ALGORITHM_SCRIPT",
	}
	GenerateAlgorithm_value = map[string]int32{
		"GENERATE_ALGORITHM_UNSPECIFIED": 0,
		"GENERATE_ALGORITHM_TIME":        1,
		"GENERATE_ALGORITHM_TIME_DATE":   2,
		"GENERATE_ALGORITHM_DEPARTMENT":  3,
		"GENERATE_ALGORITHM_COMPANY":     4,
		"GENERATE_ALGORITHM_SCRIPT":      5,
	}
)

func (x GenerateAlgorithm) Enum() *GenerateAlgorithm {
	p := new(GenerateAlgorithm)
	*p = x
	return p
}

func (x GenerateAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_generate_service_proto_enumTypes[1].Descriptor()
}

func (GenerateAlgorithm) Type() protoreflect.EnumType {
	return &file_v1_generate_service_proto_enumTypes[1]
}

func (x GenerateAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateAlgorithm.Descriptor instead.
func (GenerateAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{1}
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_v1_generate_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{0}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type AlgoValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ValueType:
	//
	//	*AlgoValue_SingleString
	//	*AlgoValue_StringList
	ValueType     isAlgoValue_ValueType `protobuf_oneof:"value_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgoValue) Reset() {
	*x = AlgoValue{}
	mi := &file_v1_generate_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgoValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgoValue) ProtoMessage() {}

func (x *AlgoValue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgoValue.ProtoReflect.Descriptor instead.
func (*AlgoValue) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{1}
}

func (x *AlgoValue) GetValueType() isAlgoValue_ValueType {
	if x != nil {
		return x.ValueType
	}
	return nil
}

func (x *AlgoValue) GetSingleString() string {
	if x != nil {
		if x, ok := x.ValueType.(*AlgoValue_SingleString); ok {
			return x.SingleString
		}
	}
	return ""
}

func (x *AlgoValue) GetStringList() *StringList {
	if x != nil {
		if x, ok := x.ValueType.(*AlgoValue_StringList); ok {
			return x.StringList
		}
	}
	return nil
}

type isAlgoValue_ValueType interface {
	isAlgoValue_ValueType()
}

type AlgoValue_SingleString struct {
	SingleString string `protobuf:"bytes,1,opt,name=single_string,json=singleString,proto3,oneof"`
}

type AlgoValue_StringList struct {
	StringList *StringList `protobuf:"bytes,2,opt,name=string_list,json=stringList,proto3,oneof"`
}

func (*AlgoValue_SingleString) isAlgoValue_ValueType() {}

func (*AlgoValue_StringList) isAlgoValue_ValueType() {}

type Rule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category        RuleCategory           `protobuf:"varint,4,opt,name=category,proto3,enum=woxqaq.v1.RuleCategory" json:"category,omitempty"`
	Enable          bool                   `protobuf:"varint,5,opt,name=enable,proto3" json:"enable,omitempty"`
	ColumnCondition string                 `protobuf:"bytes,6,opt,name=column_condition,json=columnCondition,proto3" json:"column_condition,omitempty"`
	EmptyRatio      float32                `protobuf:"fixed32,7,opt,name=empty_ratio,json=emptyRatio,proto3" json:"empty_ratio,omitempty"`
	Algorithm       GenerateAlgorithm      `protobuf:"varint,8,opt,name=algorithm,proto3,enum=woxqaq.v1.GenerateAlgorithm" json:"algorithm,omitempty"`
	AlgoMeta        map[string]*AlgoValue  `protobuf:"bytes,9,rep,name=algo_meta,json=algoMeta,proto3" json:"algo_meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Internal        bool                   `protobuf:"varint,10,opt,name=internal,proto3" json:"internal,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_v1_generate_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{2}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetCategory() RuleCategory {
	if x != nil {
		return x.Category
	}
	return RuleCategory_RULE_CATEGORY_UNSPECIFIED
}

func (x *Rule) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Rule) GetColumnCondition() string {
	if x != nil {
		return x.ColumnCondition
	}
	return ""
}

func (x *Rule) GetEmptyRatio() float32 {
	if x != nil {
		return x.EmptyRatio
	}
	return 0
}

func (x *Rule) GetAlgorithm() GenerateAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return GenerateAlgorithm_GENERATE_ALGORITHM_UNSPECIFIED
}

func (x *Rule) GetAlgoMeta() map[string]*AlgoValue {
	if x != nil {
		return x.AlgoMeta
	}
	return nil
}

func (x *Rule) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

type ListRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleRequest) Reset() {
	*x = ListRuleRequest{}
	mi := &file_v1_generate_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleRequest) ProtoMessage() {}

func (x *ListRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleRequest.ProtoReflect.Descriptor instead.
func (*ListRuleRequest) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleResponse) Reset() {
	*x = ListRuleResponse{}
	mi := &file_v1_generate_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleResponse) ProtoMessage() {}

func (x *ListRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleResponse.ProtoReflect.Descriptor instead.
func (*ListRuleResponse) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListRuleResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type CreateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rule          *Rule                  `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_v1_generate_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRuleRequest) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type CreateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleResponse) Reset() {
	*x = CreateRuleResponse{}
	mi := &file_v1_generate_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleResponse) ProtoMessage() {}

func (x *CreateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateRuleResponse) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRuleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UpdateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rule          *Rule                  `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_v1_generate_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRuleRequest) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type UpdateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleResponse) Reset() {
	*x = UpdateRuleResponse{}
	mi := &file_v1_generate_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleResponse) ProtoMessage() {}

func (x *UpdateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRuleResponse) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRuleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_v1_generate_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_v1_generate_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRuleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type AddRuleCatagoryRequest struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Name          string                                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Meta          *AddRuleCatagoryRequest_RuleCatagoryMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRuleCatagoryRequest) Reset() {
	*x = AddRuleCatagoryRequest{}
	mi := &file_v1_generate_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRuleCatagoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleCatagoryRequest) ProtoMessage() {}

func (x *AddRuleCatagoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleCatagoryRequest.ProtoReflect.Descriptor instead.
func (*AddRuleCatagoryRequest) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{11}
}

func (x *AddRuleCatagoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddRuleCatagoryRequest) GetMeta() *AddRuleCatagoryRequest_RuleCatagoryMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type AddRuleCatagoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRuleCatagoryResponse) Reset() {
	*x = AddRuleCatagoryResponse{}
	mi := &file_v1_generate_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRuleCatagoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleCatagoryResponse) ProtoMessage() {}

func (x *AddRuleCatagoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleCatagoryResponse.ProtoReflect.Descriptor instead.
func (*AddRuleCatagoryResponse) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddRuleCatagoryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PreviewRuleGenerateRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Name          string                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Meta          *PreviewRuleGenerateRequestAlgoMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRuleGenerateRequest) Reset() {
	*x = PreviewRuleGenerateRequest{}
	mi := &file_v1_generate_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRuleGenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRuleGenerateRequest) ProtoMessage() {}

func (x *PreviewRuleGenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRuleGenerateRequest.ProtoReflect.Descriptor instead.
func (*PreviewRuleGenerateRequest) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{13}
}

func (x *PreviewRuleGenerateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PreviewRuleGenerateRequest) GetMeta() *PreviewRuleGenerateRequestAlgoMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type PreviewRuleGenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRuleGenerateResponse) Reset() {
	*x = PreviewRuleGenerateResponse{}
	mi := &file_v1_generate_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRuleGenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRuleGenerateResponse) ProtoMessage() {}

func (x *PreviewRuleGenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRuleGenerateResponse.ProtoReflect.Descriptor instead.
func (*PreviewRuleGenerateResponse) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{14}
}

func (x *PreviewRuleGenerateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PreviewRuleGenerateResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRequest) Reset() {
	*x = GetRuleRequest{}
	mi := &file_v1_generate_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRequest) ProtoMessage() {}

func (x *GetRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRequest.ProtoReflect.Descriptor instead.
func (*GetRuleRequest) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleResponse) Reset() {
	*x = GetRuleResponse{}
	mi := &file_v1_generate_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleResponse) ProtoMessage() {}

func (x *GetRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleResponse.ProtoReflect.Descriptor instead.
func (*GetRuleResponse) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetRuleResponse) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type AddRuleCatagoryRequest_RuleCatagoryMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRuleCatagoryRequest_RuleCatagoryMeta) Reset() {
	*x = AddRuleCatagoryRequest_RuleCatagoryMeta{}
	mi := &file_v1_generate_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRuleCatagoryRequest_RuleCatagoryMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleCatagoryRequest_RuleCatagoryMeta) ProtoMessage() {}

func (x *AddRuleCatagoryRequest_RuleCatagoryMeta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleCatagoryRequest_RuleCatagoryMeta.ProtoReflect.Descriptor instead.
func (*AddRuleCatagoryRequest_RuleCatagoryMeta) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{11, 0}
}

func (x *AddRuleCatagoryRequest_RuleCatagoryMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddRuleCatagoryRequest_RuleCatagoryMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PreviewRuleGenerateRequestAlgoMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algo          GenerateAlgorithm      `protobuf:"varint,1,opt,name=algo,proto3,enum=woxqaq.v1.GenerateAlgorithm" json:"algo,omitempty"`
	AlgoMeta      map[string]*AlgoValue  `protobuf:"bytes,2,rep,name=algo_meta,json=algoMeta,proto3" json:"algo_meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRuleGenerateRequestAlgoMeta) Reset() {
	*x = PreviewRuleGenerateRequestAlgoMeta{}
	mi := &file_v1_generate_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRuleGenerateRequestAlgoMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRuleGenerateRequestAlgoMeta) ProtoMessage() {}

func (x *PreviewRuleGenerateRequestAlgoMeta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_generate_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRuleGenerateRequestAlgoMeta.ProtoReflect.Descriptor instead.
func (*PreviewRuleGenerateRequestAlgoMeta) Descriptor() ([]byte, []int) {
	return file_v1_generate_service_proto_rawDescGZIP(), []int{13, 0}
}

func (x *PreviewRuleGenerateRequestAlgoMeta) GetAlgo() GenerateAlgorithm {
	if x != nil {
		return x.Algo
	}
	return GenerateAlgorithm_GENERATE_ALGORITHM_UNSPECIFIED
}

func (x *PreviewRuleGenerateRequestAlgoMeta) GetAlgoMeta() map[string]*AlgoValue {
	if x != nil {
		return x.AlgoMeta
	}
	return nil
}

var File_v1_generate_service_proto protoreflect.FileDescriptor

const file_v1_generate_service_proto_rawDesc = "" +
	"\n" +
	"\x19v1/generate_service.proto\x12\twoxqaq.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"z\n" +
	"\tAlgoValue\x12%\n" +
	"\rsingle_string\x18\x01 \x01(\tH\x00R\fsingleString\x128\n" +
	"\vstring_list\x18\x02 \x01(\v2\x15.woxqaq.v1.StringListH\x00R\n" +
	"stringListB\f\n" +
	"\n" +
	"value_type\"\x92\x04\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x17.woxqaq.v1.RuleCategoryR\bcategory\x12\x16\n" +
	"\x06enable\x18\x05 \x01(\bR\x06enable\x12)\n" +
	"\x10column_condition\x18\x06 \x01(\tR\x0fcolumnCondition\x12\x1f\n" +
	"\vempty_ratio\x18\a \x01(\x02R\n" +
	"emptyRatio\x12:\n" +
	"\talgorithm\x18\b \x01(\x0e2\x1c.woxqaq.v1.GenerateAlgorithmR\talgorithm\x12:\n" +
	"\talgo_meta\x18\t \x03(\v2\x1d.woxqaq.v1.Rule.AlgoMetaEntryR\balgoMeta\x12\x1a\n" +
	"\binternal\x18\n" +
	" \x01(\bR\binternal\x1aQ\n" +
	"\rAlgoMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.woxqaq.v1.AlgoValueR\x05value:\x028\x01:D\xeaAA\n" +
	"\vwoxQAQ/Rule\x12\x1dorg/{orgName}/rule/{ruleName}\x12\x13org/{orgName}/rules\":\n" +
	"\x0fListRuleRequest\x12'\n" +
	"\x04name\x18\x01 \x01(\tB\x13\xe0A\x02\xfaA\r\n" +
	"\vwoxQAQ/RuleR\x04name\"9\n" +
	"\x10ListRuleResponse\x12%\n" +
	"\x05rules\x18\x01 \x03(\v2\x0f.woxqaq.v1.RuleR\x05rules\"a\n" +
	"\x11CreateRuleRequest\x12'\n" +
	"\x04name\x18\x01 \x01(\tB\x13\xe0A\x02\xfaA\r\n" +
	"\vwoxQAQ/RuleR\x04name\x12#\n" +
	"\x04rule\x18\x02 \x01(\v2\x0f.woxqaq.v1.RuleR\x04rule\"$\n" +
	"\x12CreateRuleResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"a\n" +
	"\x11UpdateRuleRequest\x12'\n" +
	"\x04name\x18\x01 \x01(\tB\x13\xe0A\x02\xfaA\r\n" +
	"\vwoxQAQ/RuleR\x04name\x12#\n" +
	"\x04rule\x18\x02 \x01(\v2\x0f.woxqaq.v1.RuleR\x04rule\"$\n" +
	"\x12UpdateRuleResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"<\n" +
	"\x11DeleteRuleRequest\x12'\n" +
	"\x04name\x18\x01 \x01(\tB\x13\xe0A\x02\xfaA\r\n" +
	"\vwoxQAQ/RuleR\x04name\"$\n" +
	"\x12DeleteRuleResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xd3\x01\n" +
	"\x16AddRuleCatagoryRequest\x12'\n" +
	"\x04name\x18\x01 \x01(\tB\x13\xe0A\x02\xfaA\r\n" +
	"\vwoxQAQ/RuleR\x04name\x12F\n" +
	"\x04meta\x18\x02 \x01(\v22.woxqaq.v1.AddRuleCatagoryRequest.RuleCatagoryMetaR\x04meta\x1aH\n" +
	"\x10RuleCatagoryMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\")\n" +
	"\x17AddRuleCatagoryResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xf6\x02\n" +
	"\x1aPreviewRuleGenerateRequest\x12'\n" +
	"\x04name\x18\x01 \x01(\tB\x13\xe0A\x02\xfaA\r\n" +
	"\vwoxQAQ/RuleR\x04name\x12B\n" +
	"\x04meta\x18\x02 \x01(\v2..woxqaq.v1.PreviewRuleGenerateRequest.algoMetaR\x04meta\x1a\xea\x01\n" +
	"\balgoMeta\x120\n" +
	"\x04algo\x18\x01 \x01(\x0e2\x1c.woxqaq.v1.GenerateAlgorithmR\x04algo\x12Y\n" +
	"\talgo_meta\x18\x02 \x03(\v2<.woxqaq.v1.PreviewRuleGenerateRequest.algoMeta.AlgoMetaEntryR\balgoMeta\x1aQ\n" +
	"\rAlgoMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.woxqaq.v1.AlgoValueR\x05value:\x028\x01\"C\n" +
	"\x1bPreviewRuleGenerateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"9\n" +
	"\x0eGetRuleRequest\x12'\n" +
	"\x04name\x18\x01 \x01(\tB\x13\xe0A\x02\xfaA\r\n" +
	"\vwoxQAQ/RuleR\x04name\"6\n" +
	"\x0fGetRuleResponse\x12#\n" +
	"\x04rule\x18\x01 \x01(\v2\x0f.woxqaq.v1.RuleR\x04rule*\xd0\x01\n" +
	"\fRuleCategory\x12\x1d\n" +
	"\x19RULE_CATEGORY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16RULE_CATEGORY_PERSONAL\x10\x01\x12\x19\n" +
	"\x15RULE_CATEGORY_PRODUCT\x10\x02\x12\x1a\n" +
	"\x16RULE_CATEGORY_COMMERCE\x10\x03\x12\x18\n" +
	"\x14RULE_CATEGORY_COMMON\x10\x04\x12\x1a\n" +
	"\x16RULE_CATEGORY_POSITION\x10\x05\x12\x18\n" +
	"\x14RULE_CATEGORY_CUSTOM\x10\x06*\xd8\x01\n" +
	"\x11GenerateAlgorithm\x12\"\n" +
	"\x1eGENERATE_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17GENERATE_ALGORITHM_TIME\x10\x01\x12 \n" +
	"\x1cGENERATE_ALGORITHM_TIME_DATE\x10\x02\x12!\n" +
	"\x1dGENERATE_ALGORITHM_DEPARTMENT\x10\x03\x12\x1e\n" +
	"\x1aGENERATE_ALGORITHM_COMPANY\x10\x04\x12\x1d\n" +
	"\x19GENERATE_ALGORITHM_SCRIPT\x10\x052\xc3\x06\n" +
	"\vRuleService\x12a\n" +
	"\aGetRule\x12\x19.woxqaq.v1.GetRuleRequest\x1a\x1a.woxqaq.v1.GetRuleResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/{name=org/*/rule/*}\x12c\n" +
	"\bListRule\x12\x1a.woxqaq.v1.ListRuleRequest\x1a\x1b.woxqaq.v1.ListRuleResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/{name=org/*/rules}\x12o\n" +
	"\n" +
	"CreateRule\x12\x1c.woxqaq.v1.CreateRuleRequest\x1a\x1d.woxqaq.v1.CreateRuleResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x04rule\"\x16/v1/{name=org/*/rules}\x12p\n" +
	"\n" +
	"UpdateRule\x12\x1c.woxqaq.v1.UpdateRuleRequest\x1a\x1d.woxqaq.v1.UpdateRuleResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x04rule\x1a\x17/v1/{name=org/*/rule/*}\x12j\n" +
	"\n" +
	"DeleteRule\x12\x1c.woxqaq.v1.DeleteRuleRequest\x1a\x1d.woxqaq.v1.DeleteRuleResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/{name=org/*/rule/*}\x12\x87\x01\n" +
	"\x0fAddRuleCatagory\x12!.woxqaq.v1.AddRuleCatagoryRequest\x1a\".woxqaq.v1.AddRuleCatagoryResponse\"-\x82\xd3\xe4\x93\x02':\x04meta\"\x1f/v1/{name=org/*/rules}/catagory\x12\x92\x01\n" +
	"\x13PreviewRuleGenerate\x12%.woxqaq.v1.PreviewRuleGenerateRequest\x1a&.woxqaq.v1.PreviewRuleGenerateResponse\",\x82\xd3\xe4\x93\x02&:\x04meta\"\x1e/v1/{name=org/*/rules}/previewB\x0eZ\fgenerated/v1b\x06proto3"

var (
	file_v1_generate_service_proto_rawDescOnce sync.Once
	file_v1_generate_service_proto_rawDescData []byte
)

func file_v1_generate_service_proto_rawDescGZIP() []byte {
	file_v1_generate_service_proto_rawDescOnce.Do(func() {
		file_v1_generate_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_generate_service_proto_rawDesc), len(file_v1_generate_service_proto_rawDesc)))
	})
	return file_v1_generate_service_proto_rawDescData
}

var file_v1_generate_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_generate_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_v1_generate_service_proto_goTypes = []any{
	(RuleCategory)(0),                               // 0: woxqaq.v1.RuleCategory
	(GenerateAlgorithm)(0),                          // 1: woxqaq.v1.GenerateAlgorithm
	(*StringList)(nil),                              // 2: woxqaq.v1.StringList
	(*AlgoValue)(nil),                               // 3: woxqaq.v1.AlgoValue
	(*Rule)(nil),                                    // 4: woxqaq.v1.Rule
	(*ListRuleRequest)(nil),                         // 5: woxqaq.v1.ListRuleRequest
	(*ListRuleResponse)(nil),                        // 6: woxqaq.v1.ListRuleResponse
	(*CreateRuleRequest)(nil),                       // 7: woxqaq.v1.CreateRuleRequest
	(*CreateRuleResponse)(nil),                      // 8: woxqaq.v1.CreateRuleResponse
	(*UpdateRuleRequest)(nil),                       // 9: woxqaq.v1.UpdateRuleRequest
	(*UpdateRuleResponse)(nil),                      // 10: woxqaq.v1.UpdateRuleResponse
	(*DeleteRuleRequest)(nil),                       // 11: woxqaq.v1.DeleteRuleRequest
	(*DeleteRuleResponse)(nil),                      // 12: woxqaq.v1.DeleteRuleResponse
	(*AddRuleCatagoryRequest)(nil),                  // 13: woxqaq.v1.AddRuleCatagoryRequest
	(*AddRuleCatagoryResponse)(nil),                 // 14: woxqaq.v1.AddRuleCatagoryResponse
	(*PreviewRuleGenerateRequest)(nil),              // 15: woxqaq.v1.PreviewRuleGenerateRequest
	(*PreviewRuleGenerateResponse)(nil),             // 16: woxqaq.v1.PreviewRuleGenerateResponse
	(*GetRuleRequest)(nil),                          // 17: woxqaq.v1.GetRuleRequest
	(*GetRuleResponse)(nil),                         // 18: woxqaq.v1.GetRuleResponse
	nil,                                             // 19: woxqaq.v1.Rule.AlgoMetaEntry
	(*AddRuleCatagoryRequest_RuleCatagoryMeta)(nil), // 20: woxqaq.v1.AddRuleCatagoryRequest.RuleCatagoryMeta
	(*PreviewRuleGenerateRequestAlgoMeta)(nil),      // 21: woxqaq.v1.PreviewRuleGenerateRequest.algoMeta
	nil, // 22: woxqaq.v1.PreviewRuleGenerateRequest.algoMeta.AlgoMetaEntry
}
var file_v1_generate_service_proto_depIdxs = []int32{
	2,  // 0: woxqaq.v1.AlgoValue.string_list:type_name -> woxqaq.v1.StringList
	0,  // 1: woxqaq.v1.Rule.category:type_name -> woxqaq.v1.RuleCategory
	1,  // 2: woxqaq.v1.Rule.algorithm:type_name -> woxqaq.v1.GenerateAlgorithm
	19, // 3: woxqaq.v1.Rule.algo_meta:type_name -> woxqaq.v1.Rule.AlgoMetaEntry
	4,  // 4: woxqaq.v1.ListRuleResponse.rules:type_name -> woxqaq.v1.Rule
	4,  // 5: woxqaq.v1.CreateRuleRequest.rule:type_name -> woxqaq.v1.Rule
	4,  // 6: woxqaq.v1.UpdateRuleRequest.rule:type_name -> woxqaq.v1.Rule
	20, // 7: woxqaq.v1.AddRuleCatagoryRequest.meta:type_name -> woxqaq.v1.AddRuleCatagoryRequest.RuleCatagoryMeta
	21, // 8: woxqaq.v1.PreviewRuleGenerateRequest.meta:type_name -> woxqaq.v1.PreviewRuleGenerateRequest.algoMeta
	4,  // 9: woxqaq.v1.GetRuleResponse.rule:type_name -> woxqaq.v1.Rule
	3,  // 10: woxqaq.v1.Rule.AlgoMetaEntry.value:type_name -> woxqaq.v1.AlgoValue
	1,  // 11: woxqaq.v1.PreviewRuleGenerateRequest.algoMeta.algo:type_name -> woxqaq.v1.GenerateAlgorithm
	22, // 12: woxqaq.v1.PreviewRuleGenerateRequest.algoMeta.algo_meta:type_name -> woxqaq.v1.PreviewRuleGenerateRequest.algoMeta.AlgoMetaEntry
	3,  // 13: woxqaq.v1.PreviewRuleGenerateRequest.algoMeta.AlgoMetaEntry.value:type_name -> woxqaq.v1.AlgoValue
	17, // 14: woxqaq.v1.RuleService.GetRule:input_type -> woxqaq.v1.GetRuleRequest
	5,  // 15: woxqaq.v1.RuleService.ListRule:input_type -> woxqaq.v1.ListRuleRequest
	7,  // 16: woxqaq.v1.RuleService.CreateRule:input_type -> woxqaq.v1.CreateRuleRequest
	9,  // 17: woxqaq.v1.RuleService.UpdateRule:input_type -> woxqaq.v1.UpdateRuleRequest
	11, // 18: woxqaq.v1.RuleService.DeleteRule:input_type -> woxqaq.v1.DeleteRuleRequest
	13, // 19: woxqaq.v1.RuleService.AddRuleCatagory:input_type -> woxqaq.v1.AddRuleCatagoryRequest
	15, // 20: woxqaq.v1.RuleService.PreviewRuleGenerate:input_type -> woxqaq.v1.PreviewRuleGenerateRequest
	18, // 21: woxqaq.v1.RuleService.GetRule:output_type -> woxqaq.v1.GetRuleResponse
	6,  // 22: woxqaq.v1.RuleService.ListRule:output_type -> woxqaq.v1.ListRuleResponse
	8,  // 23: woxqaq.v1.RuleService.CreateRule:output_type -> woxqaq.v1.CreateRuleResponse
	10, // 24: woxqaq.v1.RuleService.UpdateRule:output_type -> woxqaq.v1.UpdateRuleResponse
	12, // 25: woxqaq.v1.RuleService.DeleteRule:output_type -> woxqaq.v1.DeleteRuleResponse
	14, // 26: woxqaq.v1.RuleService.AddRuleCatagory:output_type -> woxqaq.v1.AddRuleCatagoryResponse
	16, // 27: woxqaq.v1.RuleService.PreviewRuleGenerate:output_type -> woxqaq.v1.PreviewRuleGenerateResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_generate_service_proto_init() }
func file_v1_generate_service_proto_init() {
	if File_v1_generate_service_proto != nil {
		return
	}
	file_v1_generate_service_proto_msgTypes[1].OneofWrappers = []any{
		(*AlgoValue_SingleString)(nil),
		(*AlgoValue_StringList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_generate_service_proto_rawDesc), len(file_v1_generate_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_generate_service_proto_goTypes,
		DependencyIndexes: file_v1_generate_service_proto_depIdxs,
		EnumInfos:         file_v1_generate_service_proto_enumTypes,
		MessageInfos:      file_v1_generate_service_proto_msgTypes,
	}.Build()
	File_v1_generate_service_proto = out.File
	file_v1_generate_service_proto_goTypes = nil
	file_v1_generate_service_proto_depIdxs = nil
}
