// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/issue_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerKind int32

const (
	TriggerKind_TRIGGER_KIND_UNSPECIFIED TriggerKind = 0
	TriggerKind_CURRENT                  TriggerKind = 1
	TriggerKind_CRON                     TriggerKind = 2
)

// Enum value maps for TriggerKind.
var (
	TriggerKind_name = map[int32]string{
		0: "TRIGGER_KIND_UNSPECIFIED",
		1: "CURRENT",
		2: "CRON",
	}
	TriggerKind_value = map[string]int32{
		"TRIGGER_KIND_UNSPECIFIED": 0,
		"CURRENT":                  1,
		"CRON":                     2,
	}
)

func (x TriggerKind) Enum() *TriggerKind {
	p := new(TriggerKind)
	*p = x
	return p
}

func (x TriggerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_issue_service_proto_enumTypes[0].Descriptor()
}

func (TriggerKind) Type() protoreflect.EnumType {
	return &file_v1_issue_service_proto_enumTypes[0]
}

func (x TriggerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerKind.Descriptor instead.
func (TriggerKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{0}
}

type IssueKind int32

const (
	IssueKind_ISSUE_KIND_UNSPECIFIED IssueKind = 0
	IssueKind_DATA_IMPORT            IssueKind = 1
	IssueKind_DATA_EXPORT            IssueKind = 2
	IssueKind_DATA_GENERATE          IssueKind = 3
)

// Enum value maps for IssueKind.
var (
	IssueKind_name = map[int32]string{
		0: "ISSUE_KIND_UNSPECIFIED",
		1: "DATA_IMPORT",
		2: "DATA_EXPORT",
		3: "DATA_GENERATE",
	}
	IssueKind_value = map[string]int32{
		"ISSUE_KIND_UNSPECIFIED": 0,
		"DATA_IMPORT":            1,
		"DATA_EXPORT":            2,
		"DATA_GENERATE":          3,
	}
)

func (x IssueKind) Enum() *IssueKind {
	p := new(IssueKind)
	*p = x
	return p
}

func (x IssueKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IssueKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_issue_service_proto_enumTypes[1].Descriptor()
}

func (IssueKind) Type() protoreflect.EnumType {
	return &file_v1_issue_service_proto_enumTypes[1]
}

func (x IssueKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IssueKind.Descriptor instead.
func (IssueKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{1}
}

type IssueStatus int32

const (
	IssueStatus_ISSUE_STATUS_UNSPECIFIED IssueStatus = 0
	IssueStatus_NOT_START                IssueStatus = 1
	IssueStatus_PRE_CHECK                IssueStatus = 2
	IssueStatus_PRE_CHECK_SUCCESS        IssueStatus = 3
	IssueStatus_PRE_CHECK_FAILED         IssueStatus = 4
	IssueStatus_APPROVING                IssueStatus = 5
	IssueStatus_APPROVED                 IssueStatus = 6
	IssueStatus_NOT_APPROVED             IssueStatus = 7
)

// Enum value maps for IssueStatus.
var (
	IssueStatus_name = map[int32]string{
		0: "ISSUE_STATUS_UNSPECIFIED",
		1: "NOT_START",
		2: "PRE_CHECK",
		3: "PRE_CHECK_SUCCESS",
		4: "PRE_CHECK_FAILED",
		5: "APPROVING",
		6: "APPROVED",
		7: "NOT_APPROVED",
	}
	IssueStatus_value = map[string]int32{
		"ISSUE_STATUS_UNSPECIFIED": 0,
		"NOT_START":                1,
		"PRE_CHECK":                2,
		"PRE_CHECK_SUCCESS":        3,
		"PRE_CHECK_FAILED":         4,
		"APPROVING":                5,
		"APPROVED":                 6,
		"NOT_APPROVED":             7,
	}
)

func (x IssueStatus) Enum() *IssueStatus {
	p := new(IssueStatus)
	*p = x
	return p
}

func (x IssueStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IssueStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_issue_service_proto_enumTypes[2].Descriptor()
}

func (IssueStatus) Type() protoreflect.EnumType {
	return &file_v1_issue_service_proto_enumTypes[2]
}

func (x IssueStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IssueStatus.Descriptor instead.
func (IssueStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{2}
}

type ApprovalStep_Type int32

const (
	ApprovalStep_TYPE_UNSPECIFIED ApprovalStep_Type = 0
	ApprovalStep_ALL              ApprovalStep_Type = 1
	ApprovalStep_ANY              ApprovalStep_Type = 2
)

// Enum value maps for ApprovalStep_Type.
var (
	ApprovalStep_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "ALL",
		2: "ANY",
	}
	ApprovalStep_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"ALL":              1,
		"ANY":              2,
	}
)

func (x ApprovalStep_Type) Enum() *ApprovalStep_Type {
	p := new(ApprovalStep_Type)
	*p = x
	return p
}

func (x ApprovalStep_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalStep_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_issue_service_proto_enumTypes[3].Descriptor()
}

func (ApprovalStep_Type) Type() protoreflect.EnumType {
	return &file_v1_issue_service_proto_enumTypes[3]
}

func (x ApprovalStep_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalStep_Type.Descriptor instead.
func (ApprovalStep_Type) EnumDescriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{3, 0}
}

type ApprovalNode_Type int32

const (
	ApprovalNode_TYPE_UNSPECIFIED ApprovalNode_Type = 0
	ApprovalNode_ANY_IN_GROUP     ApprovalNode_Type = 1
)

// Enum value maps for ApprovalNode_Type.
var (
	ApprovalNode_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "ANY_IN_GROUP",
	}
	ApprovalNode_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"ANY_IN_GROUP":     1,
	}
)

func (x ApprovalNode_Type) Enum() *ApprovalNode_Type {
	p := new(ApprovalNode_Type)
	*p = x
	return p
}

func (x ApprovalNode_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalNode_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_issue_service_proto_enumTypes[4].Descriptor()
}

func (ApprovalNode_Type) Type() protoreflect.EnumType {
	return &file_v1_issue_service_proto_enumTypes[4]
}

func (x ApprovalNode_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalNode_Type.Descriptor instead.
func (ApprovalNode_Type) EnumDescriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{4, 0}
}

type ApprovalNodeNotifyConfig_NotifyType int32

const (
	ApprovalNodeNotifyConfig_TYPE_UNSPECIFIED ApprovalNodeNotifyConfig_NotifyType = 0
	ApprovalNodeNotifyConfig_SITE_NOTIFY      ApprovalNodeNotifyConfig_NotifyType = 1
	ApprovalNodeNotifyConfig_SMS              ApprovalNodeNotifyConfig_NotifyType = 2
	ApprovalNodeNotifyConfig_EMAIL            ApprovalNodeNotifyConfig_NotifyType = 3
	ApprovalNodeNotifyConfig_PHONE            ApprovalNodeNotifyConfig_NotifyType = 4
	ApprovalNodeNotifyConfig_WEBHOOK          ApprovalNodeNotifyConfig_NotifyType = 5
)

// Enum value maps for ApprovalNodeNotifyConfig_NotifyType.
var (
	ApprovalNodeNotifyConfig_NotifyType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "SITE_NOTIFY",
		2: "SMS",
		3: "EMAIL",
		4: "PHONE",
		5: "WEBHOOK",
	}
	ApprovalNodeNotifyConfig_NotifyType_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"SITE_NOTIFY":      1,
		"SMS":              2,
		"EMAIL":            3,
		"PHONE":            4,
		"WEBHOOK":          5,
	}
)

func (x ApprovalNodeNotifyConfig_NotifyType) Enum() *ApprovalNodeNotifyConfig_NotifyType {
	p := new(ApprovalNodeNotifyConfig_NotifyType)
	*p = x
	return p
}

func (x ApprovalNodeNotifyConfig_NotifyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalNodeNotifyConfig_NotifyType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_issue_service_proto_enumTypes[5].Descriptor()
}

func (ApprovalNodeNotifyConfig_NotifyType) Type() protoreflect.EnumType {
	return &file_v1_issue_service_proto_enumTypes[5]
}

func (x ApprovalNodeNotifyConfig_NotifyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalNodeNotifyConfig_NotifyType.Descriptor instead.
func (ApprovalNodeNotifyConfig_NotifyType) EnumDescriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{5, 0}
}

type ApprovalNodeNotifyConfig_Receiver int32

const (
	ApprovalNodeNotifyConfig_RECEIVER_UNSPECIFIED ApprovalNodeNotifyConfig_Receiver = 0
	ApprovalNodeNotifyConfig_APPROVER             ApprovalNodeNotifyConfig_Receiver = 1
	ApprovalNodeNotifyConfig_COMMITTER            ApprovalNodeNotifyConfig_Receiver = 2
	ApprovalNodeNotifyConfig_EXECUTOR             ApprovalNodeNotifyConfig_Receiver = 3
	ApprovalNodeNotifyConfig_CUSTOM               ApprovalNodeNotifyConfig_Receiver = 4
)

// Enum value maps for ApprovalNodeNotifyConfig_Receiver.
var (
	ApprovalNodeNotifyConfig_Receiver_name = map[int32]string{
		0: "RECEIVER_UNSPECIFIED",
		1: "APPROVER",
		2: "COMMITTER",
		3: "EXECUTOR",
		4: "CUSTOM",
	}
	ApprovalNodeNotifyConfig_Receiver_value = map[string]int32{
		"RECEIVER_UNSPECIFIED": 0,
		"APPROVER":             1,
		"COMMITTER":            2,
		"EXECUTOR":             3,
		"CUSTOM":               4,
	}
)

func (x ApprovalNodeNotifyConfig_Receiver) Enum() *ApprovalNodeNotifyConfig_Receiver {
	p := new(ApprovalNodeNotifyConfig_Receiver)
	*p = x
	return p
}

func (x ApprovalNodeNotifyConfig_Receiver) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalNodeNotifyConfig_Receiver) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_issue_service_proto_enumTypes[6].Descriptor()
}

func (ApprovalNodeNotifyConfig_Receiver) Type() protoreflect.EnumType {
	return &file_v1_issue_service_proto_enumTypes[6]
}

func (x ApprovalNodeNotifyConfig_Receiver) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalNodeNotifyConfig_Receiver.Descriptor instead.
func (ApprovalNodeNotifyConfig_Receiver) EnumDescriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{5, 1}
}

type Issue_Approver_Status int32

const (
	Issue_Approver_STATUS_UNSPECIFIED Issue_Approver_Status = 0
	Issue_Approver_PENDING            Issue_Approver_Status = 1
	Issue_Approver_APPROVED           Issue_Approver_Status = 2
	Issue_Approver_REJECTED           Issue_Approver_Status = 3
)

// Enum value maps for Issue_Approver_Status.
var (
	Issue_Approver_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "APPROVED",
		3: "REJECTED",
	}
	Issue_Approver_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"PENDING":            1,
		"APPROVED":           2,
		"REJECTED":           3,
	}
)

func (x Issue_Approver_Status) Enum() *Issue_Approver_Status {
	p := new(Issue_Approver_Status)
	*p = x
	return p
}

func (x Issue_Approver_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Issue_Approver_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_issue_service_proto_enumTypes[7].Descriptor()
}

func (Issue_Approver_Status) Type() protoreflect.EnumType {
	return &file_v1_issue_service_proto_enumTypes[7]
}

func (x Issue_Approver_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Issue_Approver_Status.Descriptor instead.
func (Issue_Approver_Status) EnumDescriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{6, 0, 0}
}

type ListIssueRequest_IssueRole int32

const (
	ListIssueRequest_ISSUE_ROLE_UNSPECIFIED ListIssueRequest_IssueRole = 0
	ListIssueRequest_COMMITTER              ListIssueRequest_IssueRole = 1
	ListIssueRequest_TO_APPROVE             ListIssueRequest_IssueRole = 2
	ListIssueRequest_TO_EXECUTE             ListIssueRequest_IssueRole = 3
	ListIssueRequest_APPROVED               ListIssueRequest_IssueRole = 4
	ListIssueRequest_EXECUTED               ListIssueRequest_IssueRole = 5
)

// Enum value maps for ListIssueRequest_IssueRole.
var (
	ListIssueRequest_IssueRole_name = map[int32]string{
		0: "ISSUE_ROLE_UNSPECIFIED",
		1: "COMMITTER",
		2: "TO_APPROVE",
		3: "TO_EXECUTE",
		4: "APPROVED",
		5: "EXECUTED",
	}
	ListIssueRequest_IssueRole_value = map[string]int32{
		"ISSUE_ROLE_UNSPECIFIED": 0,
		"COMMITTER":              1,
		"TO_APPROVE":             2,
		"TO_EXECUTE":             3,
		"APPROVED":               4,
		"EXECUTED":               5,
	}
)

func (x ListIssueRequest_IssueRole) Enum() *ListIssueRequest_IssueRole {
	p := new(ListIssueRequest_IssueRole)
	*p = x
	return p
}

func (x ListIssueRequest_IssueRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListIssueRequest_IssueRole) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_issue_service_proto_enumTypes[8].Descriptor()
}

func (ListIssueRequest_IssueRole) Type() protoreflect.EnumType {
	return &file_v1_issue_service_proto_enumTypes[8]
}

func (x ListIssueRequest_IssueRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListIssueRequest_IssueRole.Descriptor instead.
func (ListIssueRequest_IssueRole) EnumDescriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{15, 0}
}

type IssueDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ded           *DataExportDetail      `protobuf:"bytes,1,opt,name=ded,proto3" json:"ded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueDetail) Reset() {
	*x = IssueDetail{}
	mi := &file_v1_issue_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueDetail) ProtoMessage() {}

func (x *IssueDetail) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueDetail.ProtoReflect.Descriptor instead.
func (*IssueDetail) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{0}
}

func (x *IssueDetail) GetDed() *DataExportDetail {
	if x != nil {
		return x.Ded
	}
	return nil
}

type ApprovalTemplate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Flow             *ApprovalFlow          `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RequiredApprover []string               `protobuf:"bytes,4,rep,name=required_approver,json=requiredApprover,proto3" json:"required_approver,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApprovalTemplate) Reset() {
	*x = ApprovalTemplate{}
	mi := &file_v1_issue_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalTemplate) ProtoMessage() {}

func (x *ApprovalTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalTemplate.ProtoReflect.Descriptor instead.
func (*ApprovalTemplate) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{1}
}

func (x *ApprovalTemplate) GetFlow() *ApprovalFlow {
	if x != nil {
		return x.Flow
	}
	return nil
}

func (x *ApprovalTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApprovalTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApprovalTemplate) GetRequiredApprover() []string {
	if x != nil {
		return x.RequiredApprover
	}
	return nil
}

type ApprovalFlow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*ApprovalStep        `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalFlow) Reset() {
	*x = ApprovalFlow{}
	mi := &file_v1_issue_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalFlow) ProtoMessage() {}

func (x *ApprovalFlow) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalFlow.ProtoReflect.Descriptor instead.
func (*ApprovalFlow) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{2}
}

func (x *ApprovalFlow) GetSteps() []*ApprovalStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type ApprovalStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ApprovalStep_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=woxqaq.v1.ApprovalStep_Type" json:"type,omitempty"`
	Nodes         []*ApprovalNode        `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalStep) Reset() {
	*x = ApprovalStep{}
	mi := &file_v1_issue_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalStep) ProtoMessage() {}

func (x *ApprovalStep) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalStep.ProtoReflect.Descriptor instead.
func (*ApprovalStep) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{3}
}

func (x *ApprovalStep) GetType() ApprovalStep_Type {
	if x != nil {
		return x.Type
	}
	return ApprovalStep_TYPE_UNSPECIFIED
}

func (x *ApprovalStep) GetNodes() []*ApprovalNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ApprovalNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ApprovalNode_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=woxqaq.v1.ApprovalNode_Type" json:"type,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalNode) Reset() {
	*x = ApprovalNode{}
	mi := &file_v1_issue_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalNode) ProtoMessage() {}

func (x *ApprovalNode) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalNode.ProtoReflect.Descriptor instead.
func (*ApprovalNode) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{4}
}

func (x *ApprovalNode) GetType() ApprovalNode_Type {
	if x != nil {
		return x.Type
	}
	return ApprovalNode_TYPE_UNSPECIFIED
}

func (x *ApprovalNode) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ApprovalNodeNotifyConfig struct {
	state             protoimpl.MessageState                       `protogen:"open.v1"`
	NotifyTypes       map[bool]ApprovalNodeNotifyConfig_NotifyType `protobuf:"bytes,1,rep,name=notify_types,json=notifyTypes,proto3" json:"notify_types,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=woxqaq.v1.ApprovalNodeNotifyConfig_NotifyType"`
	Webhooks          []string                                     `protobuf:"bytes,2,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	AvailableReceiver []ApprovalNodeNotifyConfig_Receiver          `protobuf:"varint,3,rep,packed,name=available_receiver,json=availableReceiver,proto3,enum=woxqaq.v1.ApprovalNodeNotifyConfig_Receiver" json:"available_receiver,omitempty"`
	SelectedReceiver  []ApprovalNodeNotifyConfig_Receiver          `protobuf:"varint,4,rep,packed,name=selected_receiver,json=selectedReceiver,proto3,enum=woxqaq.v1.ApprovalNodeNotifyConfig_Receiver" json:"selected_receiver,omitempty"`
	CustomReceivers   []string                                     `protobuf:"bytes,5,rep,name=custom_receivers,json=customReceivers,proto3" json:"custom_receivers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApprovalNodeNotifyConfig) Reset() {
	*x = ApprovalNodeNotifyConfig{}
	mi := &file_v1_issue_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalNodeNotifyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalNodeNotifyConfig) ProtoMessage() {}

func (x *ApprovalNodeNotifyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalNodeNotifyConfig.ProtoReflect.Descriptor instead.
func (*ApprovalNodeNotifyConfig) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{5}
}

func (x *ApprovalNodeNotifyConfig) GetNotifyTypes() map[bool]ApprovalNodeNotifyConfig_NotifyType {
	if x != nil {
		return x.NotifyTypes
	}
	return nil
}

func (x *ApprovalNodeNotifyConfig) GetWebhooks() []string {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

func (x *ApprovalNodeNotifyConfig) GetAvailableReceiver() []ApprovalNodeNotifyConfig_Receiver {
	if x != nil {
		return x.AvailableReceiver
	}
	return nil
}

func (x *ApprovalNodeNotifyConfig) GetSelectedReceiver() []ApprovalNodeNotifyConfig_Receiver {
	if x != nil {
		return x.SelectedReceiver
	}
	return nil
}

func (x *ApprovalNodeNotifyConfig) GetCustomReceivers() []string {
	if x != nil {
		return x.CustomReceivers
	}
	return nil
}

type Issue struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind              IssueKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=woxqaq.v1.IssueKind" json:"kind,omitempty"`
	Database          string                 `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	CreateTime        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Submitter         string                 `protobuf:"bytes,7,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Status            IssueStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=woxqaq.v1.IssueStatus" json:"status,omitempty"`
	Detail            *IssueDetail           `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail,omitempty"`
	Approvers         []*Issue_Approver      `protobuf:"bytes,10,rep,name=approvers,proto3" json:"approvers,omitempty"`
	ApprovalTemplates []*ApprovalTemplate    `protobuf:"bytes,11,rep,name=approval_templates,json=approvalTemplates,proto3" json:"approval_templates,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_v1_issue_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{6}
}

func (x *Issue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Issue) GetKind() IssueKind {
	if x != nil {
		return x.Kind
	}
	return IssueKind_ISSUE_KIND_UNSPECIFIED
}

func (x *Issue) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Issue) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Issue) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Issue) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *Issue) GetStatus() IssueStatus {
	if x != nil {
		return x.Status
	}
	return IssueStatus_ISSUE_STATUS_UNSPECIFIED
}

func (x *Issue) GetDetail() *IssueDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Issue) GetApprovers() []*Issue_Approver {
	if x != nil {
		return x.Approvers
	}
	return nil
}

func (x *Issue) GetApprovalTemplates() []*ApprovalTemplate {
	if x != nil {
		return x.ApprovalTemplates
	}
	return nil
}

type SubmitIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          IssueKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=woxqaq.v1.IssueKind" json:"kind,omitempty"`
	Detail        *IssueDetail           `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitIssueRequest) Reset() {
	*x = SubmitIssueRequest{}
	mi := &file_v1_issue_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitIssueRequest) ProtoMessage() {}

func (x *SubmitIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitIssueRequest.ProtoReflect.Descriptor instead.
func (*SubmitIssueRequest) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitIssueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitIssueRequest) GetKind() IssueKind {
	if x != nil {
		return x.Kind
	}
	return IssueKind_ISSUE_KIND_UNSPECIFIED
}

func (x *SubmitIssueRequest) GetDetail() *IssueDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type SubmitIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	IssueId       string                 `protobuf:"bytes,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitIssueResponse) Reset() {
	*x = SubmitIssueResponse{}
	mi := &file_v1_issue_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitIssueResponse) ProtoMessage() {}

func (x *SubmitIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitIssueResponse.ProtoReflect.Descriptor instead.
func (*SubmitIssueResponse) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitIssueResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubmitIssueResponse) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

type GetIssueDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueDetailRequest) Reset() {
	*x = GetIssueDetailRequest{}
	mi := &file_v1_issue_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueDetailRequest) ProtoMessage() {}

func (x *GetIssueDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueDetailRequest.ProtoReflect.Descriptor instead.
func (*GetIssueDetailRequest) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetIssueDetailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetIssueDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*GetIssueDetailResponse_Ded
	Data          isGetIssueDetailResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssueDetailResponse) Reset() {
	*x = GetIssueDetailResponse{}
	mi := &file_v1_issue_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssueDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssueDetailResponse) ProtoMessage() {}

func (x *GetIssueDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssueDetailResponse.ProtoReflect.Descriptor instead.
func (*GetIssueDetailResponse) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetIssueDetailResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetIssueDetailResponse) GetData() isGetIssueDetailResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetIssueDetailResponse) GetDed() *DataExportDetail {
	if x != nil {
		if x, ok := x.Data.(*GetIssueDetailResponse_Ded); ok {
			return x.Ded
		}
	}
	return nil
}

type isGetIssueDetailResponse_Data interface {
	isGetIssueDetailResponse_Data()
}

type GetIssueDetailResponse_Ded struct {
	Ded *DataExportDetail `protobuf:"bytes,4,opt,name=ded,proto3,oneof"`
}

func (*GetIssueDetailResponse_Ded) isGetIssueDetailResponse_Data() {}

type ApproveRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Meta          *ApproveRequestApproveMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_v1_issue_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{11}
}

func (x *ApproveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApproveRequest) GetMeta() *ApproveRequestApproveMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ApproveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	mi := &file_v1_issue_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RejectRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Meta          *RejectRequestApproveMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequest) Reset() {
	*x = RejectRequest{}
	mi := &file_v1_issue_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequest) ProtoMessage() {}

func (x *RejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequest.ProtoReflect.Descriptor instead.
func (*RejectRequest) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{13}
}

func (x *RejectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RejectRequest) GetMeta() *RejectRequestApproveMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RejectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectResponse) Reset() {
	*x = RejectResponse{}
	mi := &file_v1_issue_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectResponse) ProtoMessage() {}

func (x *RejectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectResponse.ProtoReflect.Descriptor instead.
func (*RejectResponse) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{14}
}

func (x *RejectResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListIssueRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          IssueKind                  `protobuf:"varint,2,opt,name=kind,proto3,enum=woxqaq.v1.IssueKind" json:"kind,omitempty"`
	Current       int32                      `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
	PageSize      int32                      `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        IssueStatus                `protobuf:"varint,5,opt,name=status,proto3,enum=woxqaq.v1.IssueStatus" json:"status,omitempty"`
	Role          ListIssueRequest_IssueRole `protobuf:"varint,7,opt,name=role,proto3,enum=woxqaq.v1.ListIssueRequest_IssueRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueRequest) Reset() {
	*x = ListIssueRequest{}
	mi := &file_v1_issue_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueRequest) ProtoMessage() {}

func (x *ListIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueRequest.ProtoReflect.Descriptor instead.
func (*ListIssueRequest) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListIssueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListIssueRequest) GetKind() IssueKind {
	if x != nil {
		return x.Kind
	}
	return IssueKind_ISSUE_KIND_UNSPECIFIED
}

func (x *ListIssueRequest) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ListIssueRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIssueRequest) GetStatus() IssueStatus {
	if x != nil {
		return x.Status
	}
	return IssueStatus_ISSUE_STATUS_UNSPECIFIED
}

func (x *ListIssueRequest) GetRole() ListIssueRequest_IssueRole {
	if x != nil {
		return x.Role
	}
	return ListIssueRequest_ISSUE_ROLE_UNSPECIFIED
}

type ListIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data          []*Issue               `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssueResponse) Reset() {
	*x = ListIssueResponse{}
	mi := &file_v1_issue_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssueResponse) ProtoMessage() {}

func (x *ListIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssueResponse.ProtoReflect.Descriptor instead.
func (*ListIssueResponse) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListIssueResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListIssueResponse) GetData() []*Issue {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListIssueResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIssueResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListApproveConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApproveConfigRequest) Reset() {
	*x = ListApproveConfigRequest{}
	mi := &file_v1_issue_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApproveConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApproveConfigRequest) ProtoMessage() {}

func (x *ListApproveConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApproveConfigRequest.ProtoReflect.Descriptor instead.
func (*ListApproveConfigRequest) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListApproveConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListApproveConfigResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Ok            bool                        `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data          []*ApprovalNodeNotifyConfig `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApproveConfigResponse) Reset() {
	*x = ListApproveConfigResponse{}
	mi := &file_v1_issue_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApproveConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApproveConfigResponse) ProtoMessage() {}

func (x *ListApproveConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApproveConfigResponse.ProtoReflect.Descriptor instead.
func (*ListApproveConfigResponse) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{18}
}

func (x *ListApproveConfigResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListApproveConfigResponse) GetData() []*ApprovalNodeNotifyConfig {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateApproveNotifyConfigRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          *ApprovalNodeNotifyConfig `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApproveNotifyConfigRequest) Reset() {
	*x = UpdateApproveNotifyConfigRequest{}
	mi := &file_v1_issue_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApproveNotifyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApproveNotifyConfigRequest) ProtoMessage() {}

func (x *UpdateApproveNotifyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApproveNotifyConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateApproveNotifyConfigRequest) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateApproveNotifyConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateApproveNotifyConfigRequest) GetData() *ApprovalNodeNotifyConfig {
	if x != nil {
		return x.Data
	}
	return nil
}

type Issue_Approver struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new status.
	Status        Issue_Approver_Status `protobuf:"varint,1,opt,name=status,proto3,enum=woxqaq.v1.Issue_Approver_Status" json:"status,omitempty"`
	Principal     string                `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue_Approver) Reset() {
	*x = Issue_Approver{}
	mi := &file_v1_issue_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue_Approver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue_Approver) ProtoMessage() {}

func (x *Issue_Approver) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue_Approver.ProtoReflect.Descriptor instead.
func (*Issue_Approver) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Issue_Approver) GetStatus() Issue_Approver_Status {
	if x != nil {
		return x.Status
	}
	return Issue_Approver_STATUS_UNSPECIFIED
}

func (x *Issue_Approver) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

type ApproveRequestApproveMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approver      string                 `protobuf:"bytes,1,opt,name=approver,proto3" json:"approver,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequestApproveMeta) Reset() {
	*x = ApproveRequestApproveMeta{}
	mi := &file_v1_issue_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequestApproveMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequestApproveMeta) ProtoMessage() {}

func (x *ApproveRequestApproveMeta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequestApproveMeta.ProtoReflect.Descriptor instead.
func (*ApproveRequestApproveMeta) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ApproveRequestApproveMeta) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

func (x *ApproveRequestApproveMeta) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RejectRequestApproveMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approver      string                 `protobuf:"bytes,1,opt,name=approver,proto3" json:"approver,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequestApproveMeta) Reset() {
	*x = RejectRequestApproveMeta{}
	mi := &file_v1_issue_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequestApproveMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequestApproveMeta) ProtoMessage() {}

func (x *RejectRequestApproveMeta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_issue_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequestApproveMeta.ProtoReflect.Descriptor instead.
func (*RejectRequestApproveMeta) Descriptor() ([]byte, []int) {
	return file_v1_issue_service_proto_rawDescGZIP(), []int{13, 0}
}

func (x *RejectRequestApproveMeta) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

func (x *RejectRequestApproveMeta) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_v1_issue_service_proto protoreflect.FileDescriptor

const file_v1_issue_service_proto_rawDesc = "" +
	"\n" +
	"\x16v1/issue_service.proto\x12\twoxqaq.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0ev1/issue.proto\"2\n" +
	"\vIssueDetail\x12#\n" +
	"\x03ded\x18\x01 \x01(\v2\x11.DataExportDetailR\x03ded\"\xa2\x01\n" +
	"\x10ApprovalTemplate\x12+\n" +
	"\x04flow\x18\x01 \x01(\v2\x17.woxqaq.v1.ApprovalFlowR\x04flow\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\x11required_approver\x18\x04 \x03(\tR\x10requiredApprover\"=\n" +
	"\fApprovalFlow\x12-\n" +
	"\x05steps\x18\x01 \x03(\v2\x17.woxqaq.v1.ApprovalStepR\x05steps\"\x9f\x01\n" +
	"\fApprovalStep\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.woxqaq.v1.ApprovalStep.TypeR\x04type\x12-\n" +
	"\x05nodes\x18\x02 \x03(\v2\x17.woxqaq.v1.ApprovalNodeR\x05nodes\".\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ALL\x10\x01\x12\a\n" +
	"\x03ANY\x10\x02\"\x84\x01\n" +
	"\fApprovalNode\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.woxqaq.v1.ApprovalNode.TypeR\x04type\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\".\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fANY_IN_GROUP\x10\x01\"\xeb\x05\n" +
	"\x18ApprovalNodeNotifyConfig\x12W\n" +
	"\fnotify_types\x18\x01 \x03(\v24.woxqaq.v1.ApprovalNodeNotifyConfig.NotifyTypesEntryR\vnotifyTypes\x12\x1a\n" +
	"\bwebhooks\x18\x02 \x03(\tR\bwebhooks\x12[\n" +
	"\x12available_receiver\x18\x03 \x03(\x0e2,.woxqaq.v1.ApprovalNodeNotifyConfig.ReceiverR\x11availableReceiver\x12Y\n" +
	"\x11selected_receiver\x18\x04 \x03(\x0e2,.woxqaq.v1.ApprovalNodeNotifyConfig.ReceiverR\x10selectedReceiver\x12)\n" +
	"\x10custom_receivers\x18\x05 \x03(\tR\x0fcustomReceivers\x1an\n" +
	"\x10NotifyTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12D\n" +
	"\x05value\x18\x02 \x01(\x0e2..woxqaq.v1.ApprovalNodeNotifyConfig.NotifyTypeR\x05value:\x028\x01\"_\n" +
	"\n" +
	"NotifyType\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSITE_NOTIFY\x10\x01\x12\a\n" +
	"\x03SMS\x10\x02\x12\t\n" +
	"\x05EMAIL\x10\x03\x12\t\n" +
	"\x05PHONE\x10\x04\x12\v\n" +
	"\aWEBHOOK\x10\x05\"[\n" +
	"\bReceiver\x12\x18\n" +
	"\x14RECEIVER_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bAPPROVER\x10\x01\x12\r\n" +
	"\tCOMMITTER\x10\x02\x12\f\n" +
	"\bEXECUTOR\x10\x03\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x04:I\xeaAF\n" +
	"\x1fwoxQAQ/ApprovalNodeNotifyConfig\x12#org/{orgName}/approval/notifyConfig\"\xaf\x06\n" +
	"\x05Issue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x14.woxqaq.v1.IssueKindR\x04kind\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x1c\n" +
	"\tsubmitter\x18\a \x01(\tR\tsubmitter\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.woxqaq.v1.IssueStatusR\x06status\x12.\n" +
	"\x06detail\x18\t \x01(\v2\x16.woxqaq.v1.IssueDetailR\x06detail\x127\n" +
	"\tapprovers\x18\n" +
	" \x03(\v2\x19.woxqaq.v1.Issue.ApproverR\tapprovers\x12J\n" +
	"\x12approval_templates\x18\v \x03(\v2\x1b.woxqaq.v1.ApprovalTemplateR\x11approvalTemplates\x1a\xad\x01\n" +
	"\bApprover\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .woxqaq.v1.Issue.Approver.StatusR\x06status\x12\x1c\n" +
	"\tprincipal\x18\x02 \x01(\tR\tprincipal\"I\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bAPPROVED\x10\x02\x12\f\n" +
	"\bREJECTED\x10\x03:\x9e\x01\xeaA\x9a\x01\n" +
	"\fwoxQAQ/Issue\x125org/{orgName}/instance/{instanceName}/issue/{issueId}\x12%org/{orgName}/instance/{instanceName}\x12\x1dorg/{orgName}/issue/{issueId}\x12\rorg/{orgName}\"\x82\x01\n" +
	"\x12SubmitIssueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x14.woxqaq.v1.IssueKindR\x04kind\x12.\n" +
	"\x06detail\x18\x03 \x01(\v2\x16.woxqaq.v1.IssueDetailR\x06detail\"@\n" +
	"\x13SubmitIssueResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\tR\aissueId\"A\n" +
	"\x15GetIssueDetailRequest\x12(\n" +
	"\x04name\x18\x01 \x01(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\fwoxQAQ/IssueR\x04name\"W\n" +
	"\x16GetIssueDetailResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12%\n" +
	"\x03ded\x18\x04 \x01(\v2\x11.DataExportDetailH\x00R\x03dedB\x06\n" +
	"\x04data\"\xba\x01\n" +
	"\x0eApproveRequest\x12(\n" +
	"\x04name\x18\x01 \x01(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\fwoxQAQ/IssueR\x04name\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.woxqaq.v1.ApproveRequest.approveMetaR\x04meta\x1aC\n" +
	"\vapproveMeta\x12\x1a\n" +
	"\bapprover\x18\x01 \x01(\tR\bapprover\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"!\n" +
	"\x0fApproveResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xb8\x01\n" +
	"\rRejectRequest\x12(\n" +
	"\x04name\x18\x01 \x01(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\fwoxQAQ/IssueR\x04name\x128\n" +
	"\x04meta\x18\x02 \x01(\v2$.woxqaq.v1.RejectRequest.approveMetaR\x04meta\x1aC\n" +
	"\vapproveMeta\x12\x1a\n" +
	"\bapprover\x18\x01 \x01(\tR\bapprover\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\" \n" +
	"\x0eRejectResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xff\x02\n" +
	"\x10ListIssueRequest\x12+\n" +
	"\x04name\x18\x01 \x01(\tB\x17\xe0A\x02\xfaA\x11\n" +
	"\x0fwoxQAQ/InstanceR\x04name\x12(\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x14.woxqaq.v1.IssueKindR\x04kind\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\x05R\acurrent\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.woxqaq.v1.IssueStatusR\x06status\x129\n" +
	"\x04role\x18\a \x01(\x0e2%.woxqaq.v1.ListIssueRequest.IssueRoleR\x04role\"r\n" +
	"\tIssueRole\x12\x1a\n" +
	"\x16ISSUE_ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCOMMITTER\x10\x01\x12\x0e\n" +
	"\n" +
	"TO_APPROVE\x10\x02\x12\x0e\n" +
	"\n" +
	"TO_EXECUTE\x10\x03\x12\f\n" +
	"\bAPPROVED\x10\x04\x12\f\n" +
	"\bEXECUTED\x10\x05\"|\n" +
	"\x11ListIssueResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12$\n" +
	"\x04data\x18\x02 \x03(\v2\x10.woxqaq.v1.IssueR\x04data\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"L\n" +
	"\x18ListApproveConfigRequest\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14woxQAQ/ApproveConfigR\x04name\"d\n" +
	"\x19ListApproveConfigResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x127\n" +
	"\x04data\x18\x02 \x03(\v2#.woxqaq.v1.ApprovalNodeNotifyConfigR\x04data\"\x8d\x01\n" +
	" UpdateApproveNotifyConfigRequest\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xe0A\x02\xfaA\x16\n" +
	"\x14woxQAQ/ApproveConfigR\x04name\x127\n" +
	"\x04data\x18\x02 \x01(\v2#.woxqaq.v1.ApprovalNodeNotifyConfigR\x04data*B\n" +
	"\vTriggerKind\x12\x1c\n" +
	"\x18TRIGGER_KIND_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCURRENT\x10\x01\x12\b\n" +
	"\x04CRON\x10\x02*\\\n" +
	"\tIssueKind\x12\x1a\n" +
	"\x16ISSUE_KIND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDATA_IMPORT\x10\x01\x12\x0f\n" +
	"\vDATA_EXPORT\x10\x02\x12\x11\n" +
	"\rDATA_GENERATE\x10\x03*\xa5\x01\n" +
	"\vIssueStatus\x12\x1c\n" +
	"\x18ISSUE_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tNOT_START\x10\x01\x12\r\n" +
	"\tPRE_CHECK\x10\x02\x12\x15\n" +
	"\x11PRE_CHECK_SUCCESS\x10\x03\x12\x14\n" +
	"\x10PRE_CHECK_FAILED\x10\x04\x12\r\n" +
	"\tAPPROVING\x10\x05\x12\f\n" +
	"\bAPPROVED\x10\x06\x12\x10\n" +
	"\fNOT_APPROVED\x10\a2\xd5\b\n" +
	"\fIssueService\x12\x9e\x01\n" +
	"\x0eGetIssueDetail\x12 .woxqaq.v1.GetIssueDetailRequest\x1a!.woxqaq.v1.GetIssueDetailResponse\"G\x82\xd3\xe4\x93\x02AZ\x1a\x12\x18/v1/{name=org/*/issue/*}\x12#/v1/{name=org/*/instance/*/issue/*}\x12\x7f\n" +
	"\tListIssue\x12\x1b.woxqaq.v1.ListIssueRequest\x1a\x1c.woxqaq.v1.ListIssueResponse\"7\x82\xd3\xe4\x93\x021Z\x12\x12\x10/v1/{name=org/*}\x12\x1b/v1/{name=org/*/instance/*}\x12\xb3\x01\n" +
	"\vSubmitIssue\x12\x1d.woxqaq.v1.SubmitIssueRequest\x1a\x1e.woxqaq.v1.SubmitIssueResponse\"e\x82\xd3\xe4\x93\x02_:\x06detailZ):\x06detail\"\x1f/v1/{name=org/*/issue/*}/submit\"*/v1/{name=org/*/instance/*/issue/*}/submit\x12\xa5\x01\n" +
	"\aApprove\x12\x19.woxqaq.v1.ApproveRequest\x1a\x1a.woxqaq.v1.ApproveResponse\"c\x82\xd3\xe4\x93\x02]:\x04metaZ3:\x04meta\x1a+/v1/{name=org/*/instance/*/issue/*}/approve\x1a /v1/{name=org/*/issue/*}/approve\x12\xa0\x01\n" +
	"\x06Reject\x12\x18.woxqaq.v1.RejectRequest\x1a\x19.woxqaq.v1.RejectResponse\"a\x82\xd3\xe4\x93\x02[:\x04metaZ2:\x04meta\x1a*/v1/{name=org/*/instance/*/issue/*}/reject\x1a\x1f/v1/{name=org/*/issue/*}/reject\x12\x8e\x01\n" +
	"\x11ListApproveConfig\x12#.woxqaq.v1.ListApproveConfigRequest\x1a$.woxqaq.v1.ListApproveConfigResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/{name=org/*/approval/notifyConfig}\x12\x90\x01\n" +
	"\x19UpdateApproveNotifyConfig\x12+.woxqaq.v1.UpdateApproveNotifyConfigRequest\x1a\x16.google.protobuf.Empty\".\x82\xd3\xe4\x93\x02(\x1a&/v1/{name=org/*/approval/notifyConfig}B\x0eZ\fgenerated/v1b\x06proto3"

var (
	file_v1_issue_service_proto_rawDescOnce sync.Once
	file_v1_issue_service_proto_rawDescData []byte
)

func file_v1_issue_service_proto_rawDescGZIP() []byte {
	file_v1_issue_service_proto_rawDescOnce.Do(func() {
		file_v1_issue_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_issue_service_proto_rawDesc), len(file_v1_issue_service_proto_rawDesc)))
	})
	return file_v1_issue_service_proto_rawDescData
}

var file_v1_issue_service_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_v1_issue_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_v1_issue_service_proto_goTypes = []any{
	(TriggerKind)(0),                         // 0: woxqaq.v1.TriggerKind
	(IssueKind)(0),                           // 1: woxqaq.v1.IssueKind
	(IssueStatus)(0),                         // 2: woxqaq.v1.IssueStatus
	(ApprovalStep_Type)(0),                   // 3: woxqaq.v1.ApprovalStep.Type
	(ApprovalNode_Type)(0),                   // 4: woxqaq.v1.ApprovalNode.Type
	(ApprovalNodeNotifyConfig_NotifyType)(0), // 5: woxqaq.v1.ApprovalNodeNotifyConfig.NotifyType
	(ApprovalNodeNotifyConfig_Receiver)(0),   // 6: woxqaq.v1.ApprovalNodeNotifyConfig.Receiver
	(Issue_Approver_Status)(0),               // 7: woxqaq.v1.Issue.Approver.Status
	(ListIssueRequest_IssueRole)(0),          // 8: woxqaq.v1.ListIssueRequest.IssueRole
	(*IssueDetail)(nil),                      // 9: woxqaq.v1.IssueDetail
	(*ApprovalTemplate)(nil),                 // 10: woxqaq.v1.ApprovalTemplate
	(*ApprovalFlow)(nil),                     // 11: woxqaq.v1.ApprovalFlow
	(*ApprovalStep)(nil),                     // 12: woxqaq.v1.ApprovalStep
	(*ApprovalNode)(nil),                     // 13: woxqaq.v1.ApprovalNode
	(*ApprovalNodeNotifyConfig)(nil),         // 14: woxqaq.v1.ApprovalNodeNotifyConfig
	(*Issue)(nil),                            // 15: woxqaq.v1.Issue
	(*SubmitIssueRequest)(nil),               // 16: woxqaq.v1.SubmitIssueRequest
	(*SubmitIssueResponse)(nil),              // 17: woxqaq.v1.SubmitIssueResponse
	(*GetIssueDetailRequest)(nil),            // 18: woxqaq.v1.GetIssueDetailRequest
	(*GetIssueDetailResponse)(nil),           // 19: woxqaq.v1.GetIssueDetailResponse
	(*ApproveRequest)(nil),                   // 20: woxqaq.v1.ApproveRequest
	(*ApproveResponse)(nil),                  // 21: woxqaq.v1.ApproveResponse
	(*RejectRequest)(nil),                    // 22: woxqaq.v1.RejectRequest
	(*RejectResponse)(nil),                   // 23: woxqaq.v1.RejectResponse
	(*ListIssueRequest)(nil),                 // 24: woxqaq.v1.ListIssueRequest
	(*ListIssueResponse)(nil),                // 25: woxqaq.v1.ListIssueResponse
	(*ListApproveConfigRequest)(nil),         // 26: woxqaq.v1.ListApproveConfigRequest
	(*ListApproveConfigResponse)(nil),        // 27: woxqaq.v1.ListApproveConfigResponse
	(*UpdateApproveNotifyConfigRequest)(nil), // 28: woxqaq.v1.UpdateApproveNotifyConfigRequest
	nil,                                      // 29: woxqaq.v1.ApprovalNodeNotifyConfig.NotifyTypesEntry
	(*Issue_Approver)(nil),                   // 30: woxqaq.v1.Issue.Approver
	(*ApproveRequestApproveMeta)(nil),        // 31: woxqaq.v1.ApproveRequest.approveMeta
	(*RejectRequestApproveMeta)(nil),         // 32: woxqaq.v1.RejectRequest.approveMeta
	(*DataExportDetail)(nil),                 // 33: DataExportDetail
	(*timestamppb.Timestamp)(nil),            // 34: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 35: google.protobuf.Empty
}
var file_v1_issue_service_proto_depIdxs = []int32{
	33, // 0: woxqaq.v1.IssueDetail.ded:type_name -> DataExportDetail
	11, // 1: woxqaq.v1.ApprovalTemplate.flow:type_name -> woxqaq.v1.ApprovalFlow
	12, // 2: woxqaq.v1.ApprovalFlow.steps:type_name -> woxqaq.v1.ApprovalStep
	3,  // 3: woxqaq.v1.ApprovalStep.type:type_name -> woxqaq.v1.ApprovalStep.Type
	13, // 4: woxqaq.v1.ApprovalStep.nodes:type_name -> woxqaq.v1.ApprovalNode
	4,  // 5: woxqaq.v1.ApprovalNode.type:type_name -> woxqaq.v1.ApprovalNode.Type
	29, // 6: woxqaq.v1.ApprovalNodeNotifyConfig.notify_types:type_name -> woxqaq.v1.ApprovalNodeNotifyConfig.NotifyTypesEntry
	6,  // 7: woxqaq.v1.ApprovalNodeNotifyConfig.available_receiver:type_name -> woxqaq.v1.ApprovalNodeNotifyConfig.Receiver
	6,  // 8: woxqaq.v1.ApprovalNodeNotifyConfig.selected_receiver:type_name -> woxqaq.v1.ApprovalNodeNotifyConfig.Receiver
	1,  // 9: woxqaq.v1.Issue.kind:type_name -> woxqaq.v1.IssueKind
	34, // 10: woxqaq.v1.Issue.create_time:type_name -> google.protobuf.Timestamp
	34, // 11: woxqaq.v1.Issue.update_time:type_name -> google.protobuf.Timestamp
	2,  // 12: woxqaq.v1.Issue.status:type_name -> woxqaq.v1.IssueStatus
	9,  // 13: woxqaq.v1.Issue.detail:type_name -> woxqaq.v1.IssueDetail
	30, // 14: woxqaq.v1.Issue.approvers:type_name -> woxqaq.v1.Issue.Approver
	10, // 15: woxqaq.v1.Issue.approval_templates:type_name -> woxqaq.v1.ApprovalTemplate
	1,  // 16: woxqaq.v1.SubmitIssueRequest.kind:type_name -> woxqaq.v1.IssueKind
	9,  // 17: woxqaq.v1.SubmitIssueRequest.detail:type_name -> woxqaq.v1.IssueDetail
	33, // 18: woxqaq.v1.GetIssueDetailResponse.ded:type_name -> DataExportDetail
	31, // 19: woxqaq.v1.ApproveRequest.meta:type_name -> woxqaq.v1.ApproveRequest.approveMeta
	32, // 20: woxqaq.v1.RejectRequest.meta:type_name -> woxqaq.v1.RejectRequest.approveMeta
	1,  // 21: woxqaq.v1.ListIssueRequest.kind:type_name -> woxqaq.v1.IssueKind
	2,  // 22: woxqaq.v1.ListIssueRequest.status:type_name -> woxqaq.v1.IssueStatus
	8,  // 23: woxqaq.v1.ListIssueRequest.role:type_name -> woxqaq.v1.ListIssueRequest.IssueRole
	15, // 24: woxqaq.v1.ListIssueResponse.data:type_name -> woxqaq.v1.Issue
	14, // 25: woxqaq.v1.ListApproveConfigResponse.data:type_name -> woxqaq.v1.ApprovalNodeNotifyConfig
	14, // 26: woxqaq.v1.UpdateApproveNotifyConfigRequest.data:type_name -> woxqaq.v1.ApprovalNodeNotifyConfig
	5,  // 27: woxqaq.v1.ApprovalNodeNotifyConfig.NotifyTypesEntry.value:type_name -> woxqaq.v1.ApprovalNodeNotifyConfig.NotifyType
	7,  // 28: woxqaq.v1.Issue.Approver.status:type_name -> woxqaq.v1.Issue.Approver.Status
	18, // 29: woxqaq.v1.IssueService.GetIssueDetail:input_type -> woxqaq.v1.GetIssueDetailRequest
	24, // 30: woxqaq.v1.IssueService.ListIssue:input_type -> woxqaq.v1.ListIssueRequest
	16, // 31: woxqaq.v1.IssueService.SubmitIssue:input_type -> woxqaq.v1.SubmitIssueRequest
	20, // 32: woxqaq.v1.IssueService.Approve:input_type -> woxqaq.v1.ApproveRequest
	22, // 33: woxqaq.v1.IssueService.Reject:input_type -> woxqaq.v1.RejectRequest
	26, // 34: woxqaq.v1.IssueService.ListApproveConfig:input_type -> woxqaq.v1.ListApproveConfigRequest
	28, // 35: woxqaq.v1.IssueService.UpdateApproveNotifyConfig:input_type -> woxqaq.v1.UpdateApproveNotifyConfigRequest
	19, // 36: woxqaq.v1.IssueService.GetIssueDetail:output_type -> woxqaq.v1.GetIssueDetailResponse
	25, // 37: woxqaq.v1.IssueService.ListIssue:output_type -> woxqaq.v1.ListIssueResponse
	17, // 38: woxqaq.v1.IssueService.SubmitIssue:output_type -> woxqaq.v1.SubmitIssueResponse
	21, // 39: woxqaq.v1.IssueService.Approve:output_type -> woxqaq.v1.ApproveResponse
	23, // 40: woxqaq.v1.IssueService.Reject:output_type -> woxqaq.v1.RejectResponse
	27, // 41: woxqaq.v1.IssueService.ListApproveConfig:output_type -> woxqaq.v1.ListApproveConfigResponse
	35, // 42: woxqaq.v1.IssueService.UpdateApproveNotifyConfig:output_type -> google.protobuf.Empty
	36, // [36:43] is the sub-list for method output_type
	29, // [29:36] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_v1_issue_service_proto_init() }
func file_v1_issue_service_proto_init() {
	if File_v1_issue_service_proto != nil {
		return
	}
	file_v1_issue_proto_init()
	file_v1_issue_service_proto_msgTypes[10].OneofWrappers = []any{
		(*GetIssueDetailResponse_Ded)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_issue_service_proto_rawDesc), len(file_v1_issue_service_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_issue_service_proto_goTypes,
		DependencyIndexes: file_v1_issue_service_proto_depIdxs,
		EnumInfos:         file_v1_issue_service_proto_enumTypes,
		MessageInfos:      file_v1_issue_service_proto_msgTypes,
	}.Build()
	File_v1_issue_service_proto = out.File
	file_v1_issue_service_proto_goTypes = nil
	file_v1_issue_service_proto_depIdxs = nil
}
