// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/notify_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotifyServices_Notify_FullMethodName = "/woxqaq.v1.NotifyServices/Notify"
)

// NotifyServicesClient is the client API for NotifyServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifyServicesClient interface {
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
}

type notifyServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifyServicesClient(cc grpc.ClientConnInterface) NotifyServicesClient {
	return &notifyServicesClient{cc}
}

func (c *notifyServicesClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, NotifyServices_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServicesServer is the server API for NotifyServices service.
// All implementations must embed UnimplementedNotifyServicesServer
// for forward compatibility.
type NotifyServicesServer interface {
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	mustEmbedUnimplementedNotifyServicesServer()
}

// UnimplementedNotifyServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifyServicesServer struct{}

func (UnimplementedNotifyServicesServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedNotifyServicesServer) mustEmbedUnimplementedNotifyServicesServer() {}
func (UnimplementedNotifyServicesServer) testEmbeddedByValue()                        {}

// UnsafeNotifyServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifyServicesServer will
// result in compilation errors.
type UnsafeNotifyServicesServer interface {
	mustEmbedUnimplementedNotifyServicesServer()
}

func RegisterNotifyServicesServer(s grpc.ServiceRegistrar, srv NotifyServicesServer) {
	// If the following call pancis, it indicates UnimplementedNotifyServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotifyServices_ServiceDesc, srv)
}

func _NotifyServices_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServicesServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyServices_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServicesServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotifyServices_ServiceDesc is the grpc.ServiceDesc for NotifyServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifyServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "woxqaq.v1.NotifyServices",
	HandlerType: (*NotifyServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _NotifyServices_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/notify_service.proto",
}
