// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/task_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Encoding int32

const (
	Encoding_ENCODING_UNSPECIFIED Encoding = 0
	Encoding_ENCODING_UTF8        Encoding = 1
	Encoding_ENCODING_GBK         Encoding = 2
)

// Enum value maps for Encoding.
var (
	Encoding_name = map[int32]string{
		0: "ENCODING_UNSPECIFIED",
		1: "ENCODING_UTF8",
		2: "ENCODING_GBK",
	}
	Encoding_value = map[string]int32{
		"ENCODING_UNSPECIFIED": 0,
		"ENCODING_UTF8":        1,
		"ENCODING_GBK":         2,
	}
)

func (x Encoding) Enum() *Encoding {
	p := new(Encoding)
	*p = x
	return p
}

func (x Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_task_service_proto_enumTypes[0].Descriptor()
}

func (Encoding) Type() protoreflect.EnumType {
	return &file_v1_task_service_proto_enumTypes[0]
}

func (x Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encoding.Descriptor instead.
func (Encoding) EnumDescriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{0}
}

type TriggerKind int32

const (
	TriggerKind_TRIGGER_KIND_UNSPECIFIED TriggerKind = 0
	TriggerKind_TRIGGER_KIND_CURRENT     TriggerKind = 1
	TriggerKind_TRIGGER_KIND_CRON        TriggerKind = 2
)

// Enum value maps for TriggerKind.
var (
	TriggerKind_name = map[int32]string{
		0: "TRIGGER_KIND_UNSPECIFIED",
		1: "TRIGGER_KIND_CURRENT",
		2: "TRIGGER_KIND_CRON",
	}
	TriggerKind_value = map[string]int32{
		"TRIGGER_KIND_UNSPECIFIED": 0,
		"TRIGGER_KIND_CURRENT":     1,
		"TRIGGER_KIND_CRON":        2,
	}
)

func (x TriggerKind) Enum() *TriggerKind {
	p := new(TriggerKind)
	*p = x
	return p
}

func (x TriggerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_task_service_proto_enumTypes[1].Descriptor()
}

func (TriggerKind) Type() protoreflect.EnumType {
	return &file_v1_task_service_proto_enumTypes[1]
}

func (x TriggerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerKind.Descriptor instead.
func (TriggerKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{1}
}

type ExportMethod int32

const (
	ExportMethod_EXPORT_METHOD_UNSPECIFIED ExportMethod = 0
	ExportMethod_EXPORT_METHOD_SQL         ExportMethod = 1
	ExportMethod_EXPORT_METHOD_TABLES      ExportMethod = 2
)

// Enum value maps for ExportMethod.
var (
	ExportMethod_name = map[int32]string{
		0: "EXPORT_METHOD_UNSPECIFIED",
		1: "EXPORT_METHOD_SQL",
		2: "EXPORT_METHOD_TABLES",
	}
	ExportMethod_value = map[string]int32{
		"EXPORT_METHOD_UNSPECIFIED": 0,
		"EXPORT_METHOD_SQL":         1,
		"EXPORT_METHOD_TABLES":      2,
	}
)

func (x ExportMethod) Enum() *ExportMethod {
	p := new(ExportMethod)
	*p = x
	return p
}

func (x ExportMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_task_service_proto_enumTypes[2].Descriptor()
}

func (ExportMethod) Type() protoreflect.EnumType {
	return &file_v1_task_service_proto_enumTypes[2]
}

func (x ExportMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportMethod.Descriptor instead.
func (ExportMethod) EnumDescriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{2}
}

type ExportContent int32

const (
	ExportContent_EXPORT_CONTENT_UNSPECIFIED ExportContent = 0
	ExportContent_EXPORT_CONTENT_DATA        ExportContent = 1
	ExportContent_EXPORT_CONTENT_STRUCT      ExportContent = 2
	ExportContent_EXPORT_CONTENT_ALL         ExportContent = 3
)

// Enum value maps for ExportContent.
var (
	ExportContent_name = map[int32]string{
		0: "EXPORT_CONTENT_UNSPECIFIED",
		1: "EXPORT_CONTENT_DATA",
		2: "EXPORT_CONTENT_STRUCT",
		3: "EXPORT_CONTENT_ALL",
	}
	ExportContent_value = map[string]int32{
		"EXPORT_CONTENT_UNSPECIFIED": 0,
		"EXPORT_CONTENT_DATA":        1,
		"EXPORT_CONTENT_STRUCT":      2,
		"EXPORT_CONTENT_ALL":         3,
	}
)

func (x ExportContent) Enum() *ExportContent {
	p := new(ExportContent)
	*p = x
	return p
}

func (x ExportContent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportContent) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_task_service_proto_enumTypes[3].Descriptor()
}

func (ExportContent) Type() protoreflect.EnumType {
	return &file_v1_task_service_proto_enumTypes[3]
}

func (x ExportContent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportContent.Descriptor instead.
func (ExportContent) EnumDescriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{3}
}

type ExportType int32

const (
	ExportType_EXPORT_TYPE_UNSPECIFIED ExportType = 0
	ExportType_EXPORT_TYPE_CSV         ExportType = 1
	ExportType_EXPORT_TYPE_EXCEL       ExportType = 2
)

// Enum value maps for ExportType.
var (
	ExportType_name = map[int32]string{
		0: "EXPORT_TYPE_UNSPECIFIED",
		1: "EXPORT_TYPE_CSV",
		2: "EXPORT_TYPE_EXCEL",
	}
	ExportType_value = map[string]int32{
		"EXPORT_TYPE_UNSPECIFIED": 0,
		"EXPORT_TYPE_CSV":         1,
		"EXPORT_TYPE_EXCEL":       2,
	}
)

func (x ExportType) Enum() *ExportType {
	p := new(ExportType)
	*p = x
	return p
}

func (x ExportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_task_service_proto_enumTypes[4].Descriptor()
}

func (ExportType) Type() protoreflect.EnumType {
	return &file_v1_task_service_proto_enumTypes[4]
}

func (x ExportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportType.Descriptor instead.
func (ExportType) EnumDescriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{4}
}

type Exec int32

const (
	Exec_EXEC_UNSPECIFIED Exec = 0
	Exec_EXEC_APPROVER    Exec = 1
	Exec_EXEC_COMMITTER   Exec = 2
	Exec_EXEC_AUTO        Exec = 3
)

// Enum value maps for Exec.
var (
	Exec_name = map[int32]string{
		0: "EXEC_UNSPECIFIED",
		1: "EXEC_APPROVER",
		2: "EXEC_COMMITTER",
		3: "EXEC_AUTO",
	}
	Exec_value = map[string]int32{
		"EXEC_UNSPECIFIED": 0,
		"EXEC_APPROVER":    1,
		"EXEC_COMMITTER":   2,
		"EXEC_AUTO":        3,
	}
)

func (x Exec) Enum() *Exec {
	p := new(Exec)
	*p = x
	return p
}

func (x Exec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Exec) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_task_service_proto_enumTypes[5].Descriptor()
}

func (Exec) Type() protoreflect.EnumType {
	return &file_v1_task_service_proto_enumTypes[5]
}

func (x Exec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Exec.Descriptor instead.
func (Exec) EnumDescriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{5}
}

type TaskKind int32

const (
	TaskKind_TASK_KIND_UNSPECIFIED   TaskKind = 0
	TaskKind_TASK_KIND_DATA_IMPORT   TaskKind = 1
	TaskKind_TASK_KIND_DATA_EXPORT   TaskKind = 2
	TaskKind_TASK_KIND_DATA_GENERATE TaskKind = 3
)

// Enum value maps for TaskKind.
var (
	TaskKind_name = map[int32]string{
		0: "TASK_KIND_UNSPECIFIED",
		1: "TASK_KIND_DATA_IMPORT",
		2: "TASK_KIND_DATA_EXPORT",
		3: "TASK_KIND_DATA_GENERATE",
	}
	TaskKind_value = map[string]int32{
		"TASK_KIND_UNSPECIFIED":   0,
		"TASK_KIND_DATA_IMPORT":   1,
		"TASK_KIND_DATA_EXPORT":   2,
		"TASK_KIND_DATA_GENERATE": 3,
	}
)

func (x TaskKind) Enum() *TaskKind {
	p := new(TaskKind)
	*p = x
	return p
}

func (x TaskKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_task_service_proto_enumTypes[6].Descriptor()
}

func (TaskKind) Type() protoreflect.EnumType {
	return &file_v1_task_service_proto_enumTypes[6]
}

func (x TaskKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskKind.Descriptor instead.
func (TaskKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{6}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED       TaskStatus = 0
	TaskStatus_TASK_STATUS_NOT_START         TaskStatus = 1
	TaskStatus_TASK_STATUS_PRE_CHECK         TaskStatus = 2
	TaskStatus_TASK_STATUS_PRE_CHECK_SUCCESS TaskStatus = 3
	TaskStatus_TASK_STATUS_PRE_CHECK_FAILED  TaskStatus = 4
	TaskStatus_TASK_STATUS_APPROVING         TaskStatus = 5
	TaskStatus_TASK_STATUS_APPROVED          TaskStatus = 6
	TaskStatus_TASK_STATUS_NOT_APPROVED      TaskStatus = 7
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_NOT_START",
		2: "TASK_STATUS_PRE_CHECK",
		3: "TASK_STATUS_PRE_CHECK_SUCCESS",
		4: "TASK_STATUS_PRE_CHECK_FAILED",
		5: "TASK_STATUS_APPROVING",
		6: "TASK_STATUS_APPROVED",
		7: "TASK_STATUS_NOT_APPROVED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED":       0,
		"TASK_STATUS_NOT_START":         1,
		"TASK_STATUS_PRE_CHECK":         2,
		"TASK_STATUS_PRE_CHECK_SUCCESS": 3,
		"TASK_STATUS_PRE_CHECK_FAILED":  4,
		"TASK_STATUS_APPROVING":         5,
		"TASK_STATUS_APPROVED":          6,
		"TASK_STATUS_NOT_APPROVED":      7,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_task_service_proto_enumTypes[7].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_v1_task_service_proto_enumTypes[7]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{7}
}

type TaskRole int32

const (
	TaskRole_TASK_ROLE_UNSPECIFIED TaskRole = 0
	TaskRole_TASK_ROLE_COMMITTER   TaskRole = 1
	TaskRole_TASK_ROLE_TO_APPROVE  TaskRole = 2
	TaskRole_TASK_ROLE_TO_EXECUTE  TaskRole = 3
	TaskRole_TASK_ROLE_APPROVED    TaskRole = 4
	TaskRole_TASK_ROLE_EXECUTED    TaskRole = 5
)

// Enum value maps for TaskRole.
var (
	TaskRole_name = map[int32]string{
		0: "TASK_ROLE_UNSPECIFIED",
		1: "TASK_ROLE_COMMITTER",
		2: "TASK_ROLE_TO_APPROVE",
		3: "TASK_ROLE_TO_EXECUTE",
		4: "TASK_ROLE_APPROVED",
		5: "TASK_ROLE_EXECUTED",
	}
	TaskRole_value = map[string]int32{
		"TASK_ROLE_UNSPECIFIED": 0,
		"TASK_ROLE_COMMITTER":   1,
		"TASK_ROLE_TO_APPROVE":  2,
		"TASK_ROLE_TO_EXECUTE":  3,
		"TASK_ROLE_APPROVED":    4,
		"TASK_ROLE_EXECUTED":    5,
	}
)

func (x TaskRole) Enum() *TaskRole {
	p := new(TaskRole)
	*p = x
	return p
}

func (x TaskRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskRole) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_task_service_proto_enumTypes[8].Descriptor()
}

func (TaskRole) Type() protoreflect.EnumType {
	return &file_v1_task_service_proto_enumTypes[8]
}

func (x TaskRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskRole.Descriptor instead.
func (TaskRole) EnumDescriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{8}
}

type TaskDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ded           *DataExportDetail      `protobuf:"bytes,1,opt,name=ded,proto3" json:"ded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDetail) Reset() {
	*x = TaskDetail{}
	mi := &file_v1_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetail) ProtoMessage() {}

func (x *TaskDetail) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetail.ProtoReflect.Descriptor instead.
func (*TaskDetail) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDetail) GetDed() *DataExportDetail {
	if x != nil {
		return x.Ded
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dsn           string                 `protobuf:"bytes,2,opt,name=dsn,proto3" json:"dsn,omitempty"`
	Kind          TaskKind               `protobuf:"varint,3,opt,name=kind,proto3,enum=woxqaq.v1.TaskKind" json:"kind,omitempty"`
	Database      string                 `protobuf:"bytes,4,opt,name=database,proto3" json:"database,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Submitter     string                 `protobuf:"bytes,7,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Status        TaskStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=woxqaq.v1.TaskStatus" json:"status,omitempty"`
	Detail        *TaskDetail            `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_v1_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Task) GetKind() TaskKind {
	if x != nil {
		return x.Kind
	}
	return TaskKind_TASK_KIND_UNSPECIFIED
}

func (x *Task) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Task) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Task) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Task) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetDetail() *TaskDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type ExportBySQL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statement     string                 `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportBySQL) Reset() {
	*x = ExportBySQL{}
	mi := &file_v1_task_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportBySQL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportBySQL) ProtoMessage() {}

func (x *ExportBySQL) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportBySQL.ProtoReflect.Descriptor instead.
func (*ExportBySQL) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *ExportBySQL) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

type ExportAccordingToTable struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	ExportAll     bool                                  `protobuf:"varint,1,opt,name=export_all,json=exportAll,proto3" json:"export_all,omitempty"`
	Content       ExportContent                         `protobuf:"varint,2,opt,name=content,proto3,enum=woxqaq.v1.ExportContent" json:"content,omitempty"`
	Option        []*ExportAccordingToTable_TableOption `protobuf:"bytes,3,rep,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAccordingToTable) Reset() {
	*x = ExportAccordingToTable{}
	mi := &file_v1_task_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAccordingToTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAccordingToTable) ProtoMessage() {}

func (x *ExportAccordingToTable) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAccordingToTable.ProtoReflect.Descriptor instead.
func (*ExportAccordingToTable) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{3}
}

func (x *ExportAccordingToTable) GetExportAll() bool {
	if x != nil {
		return x.ExportAll
	}
	return false
}

func (x *ExportAccordingToTable) GetContent() ExportContent {
	if x != nil {
		return x.Content
	}
	return ExportContent_EXPORT_CONTENT_UNSPECIFIED
}

func (x *ExportAccordingToTable) GetOption() []*ExportAccordingToTable_TableOption {
	if x != nil {
		return x.Option
	}
	return nil
}

type DataExportDetail struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Database string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Types that are valid to be assigned to ExportDetail:
	//
	//	*DataExportDetail_Ebs
	//	*DataExportDetail_Eatt
	ExportDetail  isDataExportDetail_ExportDetail `protobuf_oneof:"export_detail"`
	Type          ExportType                      `protobuf:"varint,4,opt,name=type,proto3,enum=woxqaq.v1.ExportType" json:"type,omitempty"`
	Encoding      Encoding                        `protobuf:"varint,5,opt,name=encoding,proto3,enum=woxqaq.v1.Encoding" json:"encoding,omitempty"`
	ExportReason  string                          `protobuf:"bytes,6,opt,name=export_reason,json=exportReason,proto3" json:"export_reason,omitempty"`
	Exector       Exec                            `protobuf:"varint,7,opt,name=exector,proto3,enum=woxqaq.v1.Exec" json:"exector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataExportDetail) Reset() {
	*x = DataExportDetail{}
	mi := &file_v1_task_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataExportDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataExportDetail) ProtoMessage() {}

func (x *DataExportDetail) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataExportDetail.ProtoReflect.Descriptor instead.
func (*DataExportDetail) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{4}
}

func (x *DataExportDetail) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DataExportDetail) GetExportDetail() isDataExportDetail_ExportDetail {
	if x != nil {
		return x.ExportDetail
	}
	return nil
}

func (x *DataExportDetail) GetEbs() *ExportBySQL {
	if x != nil {
		if x, ok := x.ExportDetail.(*DataExportDetail_Ebs); ok {
			return x.Ebs
		}
	}
	return nil
}

func (x *DataExportDetail) GetEatt() *ExportAccordingToTable {
	if x != nil {
		if x, ok := x.ExportDetail.(*DataExportDetail_Eatt); ok {
			return x.Eatt
		}
	}
	return nil
}

func (x *DataExportDetail) GetType() ExportType {
	if x != nil {
		return x.Type
	}
	return ExportType_EXPORT_TYPE_UNSPECIFIED
}

func (x *DataExportDetail) GetEncoding() Encoding {
	if x != nil {
		return x.Encoding
	}
	return Encoding_ENCODING_UNSPECIFIED
}

func (x *DataExportDetail) GetExportReason() string {
	if x != nil {
		return x.ExportReason
	}
	return ""
}

func (x *DataExportDetail) GetExector() Exec {
	if x != nil {
		return x.Exector
	}
	return Exec_EXEC_UNSPECIFIED
}

type isDataExportDetail_ExportDetail interface {
	isDataExportDetail_ExportDetail()
}

type DataExportDetail_Ebs struct {
	Ebs *ExportBySQL `protobuf:"bytes,2,opt,name=ebs,proto3,oneof"`
}

type DataExportDetail_Eatt struct {
	Eatt *ExportAccordingToTable `protobuf:"bytes,3,opt,name=eatt,proto3,oneof"`
}

func (*DataExportDetail_Ebs) isDataExportDetail_ExportDetail() {}

func (*DataExportDetail_Eatt) isDataExportDetail_ExportDetail() {}

type SubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          TaskKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=woxqaq.v1.TaskKind" json:"kind,omitempty"`
	Detail        *TaskDetail            `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_v1_task_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitTaskRequest) GetKind() TaskKind {
	if x != nil {
		return x.Kind
	}
	return TaskKind_TASK_KIND_UNSPECIFIED
}

func (x *SubmitTaskRequest) GetDetail() *TaskDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_v1_task_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitTaskResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubmitTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDetailRequest) Reset() {
	*x = GetTaskDetailRequest{}
	mi := &file_v1_task_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDetailRequest) ProtoMessage() {}

func (x *GetTaskDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDetailRequest.ProtoReflect.Descriptor instead.
func (*GetTaskDetailRequest) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaskDetailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTaskDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*GetTaskDetailResponse_Ded
	Data          isGetTaskDetailResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDetailResponse) Reset() {
	*x = GetTaskDetailResponse{}
	mi := &file_v1_task_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDetailResponse) ProtoMessage() {}

func (x *GetTaskDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDetailResponse.ProtoReflect.Descriptor instead.
func (*GetTaskDetailResponse) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaskDetailResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetTaskDetailResponse) GetData() isGetTaskDetailResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetTaskDetailResponse) GetDed() *DataExportDetail {
	if x != nil {
		if x, ok := x.Data.(*GetTaskDetailResponse_Ded); ok {
			return x.Ded
		}
	}
	return nil
}

type isGetTaskDetailResponse_Data interface {
	isGetTaskDetailResponse_Data()
}

type GetTaskDetailResponse_Ded struct {
	Ded *DataExportDetail `protobuf:"bytes,4,opt,name=ded,proto3,oneof"`
}

func (*GetTaskDetailResponse_Ded) isGetTaskDetailResponse_Data() {}

type ApproveRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Meta          *ApproveRequestApproveMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_v1_task_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{9}
}

func (x *ApproveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApproveRequest) GetMeta() *ApproveRequestApproveMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ApproveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	mi := &file_v1_task_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{10}
}

func (x *ApproveResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RejectRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Meta          *RejectRequestApproveMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequest) Reset() {
	*x = RejectRequest{}
	mi := &file_v1_task_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequest) ProtoMessage() {}

func (x *RejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequest.ProtoReflect.Descriptor instead.
func (*RejectRequest) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{11}
}

func (x *RejectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RejectRequest) GetMeta() *RejectRequestApproveMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RejectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectResponse) Reset() {
	*x = RejectResponse{}
	mi := &file_v1_task_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectResponse) ProtoMessage() {}

func (x *RejectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectResponse.ProtoReflect.Descriptor instead.
func (*RejectResponse) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{12}
}

func (x *RejectResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          TaskKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=woxqaq.v1.TaskKind" json:"kind,omitempty"`
	Current       int32                  `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=woxqaq.v1.TaskStatus" json:"status,omitempty"`
	Role          TaskRole               `protobuf:"varint,7,opt,name=role,proto3,enum=woxqaq.v1.TaskRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskRequest) Reset() {
	*x = ListTaskRequest{}
	mi := &file_v1_task_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskRequest) ProtoMessage() {}

func (x *ListTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskRequest.ProtoReflect.Descriptor instead.
func (*ListTaskRequest) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListTaskRequest) GetKind() TaskKind {
	if x != nil {
		return x.Kind
	}
	return TaskKind_TASK_KIND_UNSPECIFIED
}

func (x *ListTaskRequest) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *ListTaskRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTaskRequest) GetRole() TaskRole {
	if x != nil {
		return x.Role
	}
	return TaskRole_TASK_ROLE_UNSPECIFIED
}

type ListTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data          []*Task                `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskResponse) Reset() {
	*x = ListTaskResponse{}
	mi := &file_v1_task_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskResponse) ProtoMessage() {}

func (x *ListTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskResponse.ProtoReflect.Descriptor instead.
func (*ListTaskResponse) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListTaskResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListTaskResponse) GetData() []*Task {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListTaskResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTaskResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ExportAccordingToTable_TableOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	AllField      bool                   `protobuf:"varint,2,opt,name=all_field,json=allField,proto3" json:"all_field,omitempty"`
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAccordingToTable_TableOption) Reset() {
	*x = ExportAccordingToTable_TableOption{}
	mi := &file_v1_task_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAccordingToTable_TableOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAccordingToTable_TableOption) ProtoMessage() {}

func (x *ExportAccordingToTable_TableOption) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAccordingToTable_TableOption.ProtoReflect.Descriptor instead.
func (*ExportAccordingToTable_TableOption) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ExportAccordingToTable_TableOption) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ExportAccordingToTable_TableOption) GetAllField() bool {
	if x != nil {
		return x.AllField
	}
	return false
}

func (x *ExportAccordingToTable_TableOption) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ExportAccordingToTable_TableOption) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ApproveRequestApproveMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approver      string                 `protobuf:"bytes,1,opt,name=approver,proto3" json:"approver,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequestApproveMeta) Reset() {
	*x = ApproveRequestApproveMeta{}
	mi := &file_v1_task_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequestApproveMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequestApproveMeta) ProtoMessage() {}

func (x *ApproveRequestApproveMeta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequestApproveMeta.ProtoReflect.Descriptor instead.
func (*ApproveRequestApproveMeta) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ApproveRequestApproveMeta) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

func (x *ApproveRequestApproveMeta) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RejectRequestApproveMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approver      string                 `protobuf:"bytes,1,opt,name=approver,proto3" json:"approver,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequestApproveMeta) Reset() {
	*x = RejectRequestApproveMeta{}
	mi := &file_v1_task_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequestApproveMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequestApproveMeta) ProtoMessage() {}

func (x *RejectRequestApproveMeta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_task_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequestApproveMeta.ProtoReflect.Descriptor instead.
func (*RejectRequestApproveMeta) Descriptor() ([]byte, []int) {
	return file_v1_task_service_proto_rawDescGZIP(), []int{11, 0}
}

func (x *RejectRequestApproveMeta) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

func (x *RejectRequestApproveMeta) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_v1_task_service_proto protoreflect.FileDescriptor

const file_v1_task_service_proto_rawDesc = "" +
	"\n" +
	"\x15v1/task_service.proto\x12\twoxqaq.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\n" +
	"TaskDetail\x12-\n" +
	"\x03ded\x18\x01 \x01(\v2\x1b.woxqaq.v1.DataExportDetailR\x03ded\"\x80\x04\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03dsn\x18\x02 \x01(\tR\x03dsn\x12'\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x13.woxqaq.v1.TaskKindR\x04kind\x12\x1a\n" +
	"\bdatabase\x18\x04 \x01(\tR\bdatabase\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x1c\n" +
	"\tsubmitter\x18\a \x01(\tR\tsubmitter\x12-\n" +
	"\x06status\x18\b \x01(\x0e2\x15.woxqaq.v1.TaskStatusR\x06status\x12-\n" +
	"\x06detail\x18\t \x01(\v2\x15.woxqaq.v1.TaskDetailR\x06detail:\x9a\x01\xeaA\x96\x01\n" +
	"\fwoxQAQ/Issue\x123org/{orgName}/instance/{instanceName}/task/{taskId}\x12%org/{orgName}/instance/{instanceName}\x12\x1borg/{orgName}/task/{taskId}\x12\rorg/{orgName}\"+\n" +
	"\vExportBySQL\x12\x1c\n" +
	"\tstatement\x18\x01 \x01(\tR\tstatement\"\xa4\x02\n" +
	"\x16ExportAccordingToTable\x12\x1d\n" +
	"\n" +
	"export_all\x18\x01 \x01(\bR\texportAll\x122\n" +
	"\acontent\x18\x02 \x01(\x0e2\x18.woxqaq.v1.ExportContentR\acontent\x12E\n" +
	"\x06option\x18\x03 \x03(\v2-.woxqaq.v1.ExportAccordingToTable.TableOptionR\x06option\x1ap\n" +
	"\vTableOption\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x1b\n" +
	"\tall_field\x18\x02 \x01(\bR\ballField\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"\xd0\x02\n" +
	"\x10DataExportDetail\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12*\n" +
	"\x03ebs\x18\x02 \x01(\v2\x16.woxqaq.v1.ExportBySQLH\x00R\x03ebs\x127\n" +
	"\x04eatt\x18\x03 \x01(\v2!.woxqaq.v1.ExportAccordingToTableH\x00R\x04eatt\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.woxqaq.v1.ExportTypeR\x04type\x12/\n" +
	"\bencoding\x18\x05 \x01(\x0e2\x13.woxqaq.v1.EncodingR\bencoding\x12#\n" +
	"\rexport_reason\x18\x06 \x01(\tR\fexportReason\x12)\n" +
	"\aexector\x18\a \x01(\x0e2\x0f.woxqaq.v1.ExecR\aexectorB\x0f\n" +
	"\rexport_detail\"\x7f\n" +
	"\x11SubmitTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x13.woxqaq.v1.TaskKindR\x04kind\x12-\n" +
	"\x06detail\x18\x03 \x01(\v2\x15.woxqaq.v1.TaskDetailR\x06detail\"=\n" +
	"\x12SubmitTaskResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"@\n" +
	"\x14GetTaskDetailRequest\x12(\n" +
	"\x04name\x18\x01 \x01(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\fwoxQAQ/IssueR\x04name\"`\n" +
	"\x15GetTaskDetailResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12/\n" +
	"\x03ded\x18\x04 \x01(\v2\x1b.woxqaq.v1.DataExportDetailH\x00R\x03dedB\x06\n" +
	"\x04data\"\xba\x01\n" +
	"\x0eApproveRequest\x12(\n" +
	"\x04name\x18\x01 \x01(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\fwoxQAQ/IssueR\x04name\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.woxqaq.v1.ApproveRequest.approveMetaR\x04meta\x1aC\n" +
	"\vapproveMeta\x12\x1a\n" +
	"\bapprover\x18\x01 \x01(\tR\bapprover\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"!\n" +
	"\x0fApproveResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xb8\x01\n" +
	"\rRejectRequest\x12(\n" +
	"\x04name\x18\x01 \x01(\tB\x14\xe0A\x02\xfaA\x0e\n" +
	"\fwoxQAQ/IssueR\x04name\x128\n" +
	"\x04meta\x18\x02 \x01(\v2$.woxqaq.v1.RejectRequest.approveMetaR\x04meta\x1aC\n" +
	"\vapproveMeta\x12\x1a\n" +
	"\bapprover\x18\x01 \x01(\tR\bapprover\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\" \n" +
	"\x0eRejectResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xf6\x01\n" +
	"\x0fListTaskRequest\x12+\n" +
	"\x04name\x18\x01 \x01(\tB\x17\xe0A\x02\xfaA\x11\n" +
	"\x0fwoxQAQ/InstanceR\x04name\x12'\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x13.woxqaq.v1.TaskKindR\x04kind\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\x05R\acurrent\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.woxqaq.v1.TaskStatusR\x06status\x12'\n" +
	"\x04role\x18\a \x01(\x0e2\x13.woxqaq.v1.TaskRoleR\x04role\"z\n" +
	"\x10ListTaskResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\x04data\x18\x02 \x03(\v2\x0f.woxqaq.v1.TaskR\x04data\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total*I\n" +
	"\bEncoding\x12\x18\n" +
	"\x14ENCODING_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rENCODING_UTF8\x10\x01\x12\x10\n" +
	"\fENCODING_GBK\x10\x02*\\\n" +
	"\vTriggerKind\x12\x1c\n" +
	"\x18TRIGGER_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TRIGGER_KIND_CURRENT\x10\x01\x12\x15\n" +
	"\x11TRIGGER_KIND_CRON\x10\x02*^\n" +
	"\fExportMethod\x12\x1d\n" +
	"\x19EXPORT_METHOD_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EXPORT_METHOD_SQL\x10\x01\x12\x18\n" +
	"\x14EXPORT_METHOD_TABLES\x10\x02*{\n" +
	"\rExportContent\x12\x1e\n" +
	"\x1aEXPORT_CONTENT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EXPORT_CONTENT_DATA\x10\x01\x12\x19\n" +
	"\x15EXPORT_CONTENT_STRUCT\x10\x02\x12\x16\n" +
	"\x12EXPORT_CONTENT_ALL\x10\x03*U\n" +
	"\n" +
	"ExportType\x12\x1b\n" +
	"\x17EXPORT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fEXPORT_TYPE_CSV\x10\x01\x12\x15\n" +
	"\x11EXPORT_TYPE_EXCEL\x10\x02*R\n" +
	"\x04Exec\x12\x14\n" +
	"\x10EXEC_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rEXEC_APPROVER\x10\x01\x12\x12\n" +
	"\x0eEXEC_COMMITTER\x10\x02\x12\r\n" +
	"\tEXEC_AUTO\x10\x03*x\n" +
	"\bTaskKind\x12\x19\n" +
	"\x15TASK_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TASK_KIND_DATA_IMPORT\x10\x01\x12\x19\n" +
	"\x15TASK_KIND_DATA_EXPORT\x10\x02\x12\x1b\n" +
	"\x17TASK_KIND_DATA_GENERATE\x10\x03*\xf7\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TASK_STATUS_NOT_START\x10\x01\x12\x19\n" +
	"\x15TASK_STATUS_PRE_CHECK\x10\x02\x12!\n" +
	"\x1dTASK_STATUS_PRE_CHECK_SUCCESS\x10\x03\x12 \n" +
	"\x1cTASK_STATUS_PRE_CHECK_FAILED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_APPROVING\x10\x05\x12\x18\n" +
	"\x14TASK_STATUS_APPROVED\x10\x06\x12\x1c\n" +
	"\x18TASK_STATUS_NOT_APPROVED\x10\a*\xa2\x01\n" +
	"\bTaskRole\x12\x19\n" +
	"\x15TASK_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_ROLE_COMMITTER\x10\x01\x12\x18\n" +
	"\x14TASK_ROLE_TO_APPROVE\x10\x02\x12\x18\n" +
	"\x14TASK_ROLE_TO_EXECUTE\x10\x03\x12\x16\n" +
	"\x12TASK_ROLE_APPROVED\x10\x04\x12\x16\n" +
	"\x12TASK_ROLE_EXECUTED\x10\x052\x9f\x06\n" +
	"\vTaskService\x12\x99\x01\n" +
	"\rGetTaskDetail\x12\x1f.woxqaq.v1.GetTaskDetailRequest\x1a .woxqaq.v1.GetTaskDetailResponse\"E\x82\xd3\xe4\x93\x02?Z\x19\x12\x17/v1/{name=org/*/task/*}\x12\"/v1/{name=org/*/instance/*/task/*}\x12|\n" +
	"\bListTask\x12\x1a.woxqaq.v1.ListTaskRequest\x1a\x1b.woxqaq.v1.ListTaskResponse\"7\x82\xd3\xe4\x93\x021Z\x12\x12\x10/v1/{name=org/*}\x12\x1b/v1/{name=org/*/instance/*}\x12\xae\x01\n" +
	"\n" +
	"SubmitTask\x12\x1c.woxqaq.v1.SubmitTaskRequest\x1a\x1d.woxqaq.v1.SubmitTaskResponse\"c\x82\xd3\xe4\x93\x02]:\x06detailZ(:\x06detail\"\x1e/v1/{name=org/*/task/*}/submit\")/v1/{name=org/*/instance/*/task/*}/submit\x12\xa3\x01\n" +
	"\aApprove\x12\x19.woxqaq.v1.ApproveRequest\x1a\x1a.woxqaq.v1.ApproveResponse\"a\x82\xd3\xe4\x93\x02[:\x04metaZ2:\x04meta\x1a*/v1/{name=org/*/instance/*/task/*}/approve\x1a\x1f/v1/{name=org/*/task/*}/approve\x12\x9e\x01\n" +
	"\x06Reject\x12\x18.woxqaq.v1.RejectRequest\x1a\x19.woxqaq.v1.RejectResponse\"_\x82\xd3\xe4\x93\x02Y:\x04metaZ1:\x04meta\x1a)/v1/{name=org/*/instance/*/task/*}/reject\x1a\x1e/v1/{name=org/*/task/*}/rejectB\x0eZ\fgenerated/v1b\x06proto3"

var (
	file_v1_task_service_proto_rawDescOnce sync.Once
	file_v1_task_service_proto_rawDescData []byte
)

func file_v1_task_service_proto_rawDescGZIP() []byte {
	file_v1_task_service_proto_rawDescOnce.Do(func() {
		file_v1_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_task_service_proto_rawDesc), len(file_v1_task_service_proto_rawDesc)))
	})
	return file_v1_task_service_proto_rawDescData
}

var file_v1_task_service_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_v1_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_v1_task_service_proto_goTypes = []any{
	(Encoding)(0),                              // 0: woxqaq.v1.Encoding
	(TriggerKind)(0),                           // 1: woxqaq.v1.TriggerKind
	(ExportMethod)(0),                          // 2: woxqaq.v1.ExportMethod
	(ExportContent)(0),                         // 3: woxqaq.v1.ExportContent
	(ExportType)(0),                            // 4: woxqaq.v1.ExportType
	(Exec)(0),                                  // 5: woxqaq.v1.Exec
	(TaskKind)(0),                              // 6: woxqaq.v1.TaskKind
	(TaskStatus)(0),                            // 7: woxqaq.v1.TaskStatus
	(TaskRole)(0),                              // 8: woxqaq.v1.TaskRole
	(*TaskDetail)(nil),                         // 9: woxqaq.v1.TaskDetail
	(*Task)(nil),                               // 10: woxqaq.v1.Task
	(*ExportBySQL)(nil),                        // 11: woxqaq.v1.ExportBySQL
	(*ExportAccordingToTable)(nil),             // 12: woxqaq.v1.ExportAccordingToTable
	(*DataExportDetail)(nil),                   // 13: woxqaq.v1.DataExportDetail
	(*SubmitTaskRequest)(nil),                  // 14: woxqaq.v1.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),                 // 15: woxqaq.v1.SubmitTaskResponse
	(*GetTaskDetailRequest)(nil),               // 16: woxqaq.v1.GetTaskDetailRequest
	(*GetTaskDetailResponse)(nil),              // 17: woxqaq.v1.GetTaskDetailResponse
	(*ApproveRequest)(nil),                     // 18: woxqaq.v1.ApproveRequest
	(*ApproveResponse)(nil),                    // 19: woxqaq.v1.ApproveResponse
	(*RejectRequest)(nil),                      // 20: woxqaq.v1.RejectRequest
	(*RejectResponse)(nil),                     // 21: woxqaq.v1.RejectResponse
	(*ListTaskRequest)(nil),                    // 22: woxqaq.v1.ListTaskRequest
	(*ListTaskResponse)(nil),                   // 23: woxqaq.v1.ListTaskResponse
	(*ExportAccordingToTable_TableOption)(nil), // 24: woxqaq.v1.ExportAccordingToTable.TableOption
	(*ApproveRequestApproveMeta)(nil),          // 25: woxqaq.v1.ApproveRequest.approveMeta
	(*RejectRequestApproveMeta)(nil),           // 26: woxqaq.v1.RejectRequest.approveMeta
	(*timestamppb.Timestamp)(nil),              // 27: google.protobuf.Timestamp
}
var file_v1_task_service_proto_depIdxs = []int32{
	13, // 0: woxqaq.v1.TaskDetail.ded:type_name -> woxqaq.v1.DataExportDetail
	6,  // 1: woxqaq.v1.Task.kind:type_name -> woxqaq.v1.TaskKind
	27, // 2: woxqaq.v1.Task.create_time:type_name -> google.protobuf.Timestamp
	27, // 3: woxqaq.v1.Task.update_time:type_name -> google.protobuf.Timestamp
	7,  // 4: woxqaq.v1.Task.status:type_name -> woxqaq.v1.TaskStatus
	9,  // 5: woxqaq.v1.Task.detail:type_name -> woxqaq.v1.TaskDetail
	3,  // 6: woxqaq.v1.ExportAccordingToTable.content:type_name -> woxqaq.v1.ExportContent
	24, // 7: woxqaq.v1.ExportAccordingToTable.option:type_name -> woxqaq.v1.ExportAccordingToTable.TableOption
	11, // 8: woxqaq.v1.DataExportDetail.ebs:type_name -> woxqaq.v1.ExportBySQL
	12, // 9: woxqaq.v1.DataExportDetail.eatt:type_name -> woxqaq.v1.ExportAccordingToTable
	4,  // 10: woxqaq.v1.DataExportDetail.type:type_name -> woxqaq.v1.ExportType
	0,  // 11: woxqaq.v1.DataExportDetail.encoding:type_name -> woxqaq.v1.Encoding
	5,  // 12: woxqaq.v1.DataExportDetail.exector:type_name -> woxqaq.v1.Exec
	6,  // 13: woxqaq.v1.SubmitTaskRequest.kind:type_name -> woxqaq.v1.TaskKind
	9,  // 14: woxqaq.v1.SubmitTaskRequest.detail:type_name -> woxqaq.v1.TaskDetail
	13, // 15: woxqaq.v1.GetTaskDetailResponse.ded:type_name -> woxqaq.v1.DataExportDetail
	25, // 16: woxqaq.v1.ApproveRequest.meta:type_name -> woxqaq.v1.ApproveRequest.approveMeta
	26, // 17: woxqaq.v1.RejectRequest.meta:type_name -> woxqaq.v1.RejectRequest.approveMeta
	6,  // 18: woxqaq.v1.ListTaskRequest.kind:type_name -> woxqaq.v1.TaskKind
	7,  // 19: woxqaq.v1.ListTaskRequest.status:type_name -> woxqaq.v1.TaskStatus
	8,  // 20: woxqaq.v1.ListTaskRequest.role:type_name -> woxqaq.v1.TaskRole
	10, // 21: woxqaq.v1.ListTaskResponse.data:type_name -> woxqaq.v1.Task
	16, // 22: woxqaq.v1.TaskService.GetTaskDetail:input_type -> woxqaq.v1.GetTaskDetailRequest
	22, // 23: woxqaq.v1.TaskService.ListTask:input_type -> woxqaq.v1.ListTaskRequest
	14, // 24: woxqaq.v1.TaskService.SubmitTask:input_type -> woxqaq.v1.SubmitTaskRequest
	18, // 25: woxqaq.v1.TaskService.Approve:input_type -> woxqaq.v1.ApproveRequest
	20, // 26: woxqaq.v1.TaskService.Reject:input_type -> woxqaq.v1.RejectRequest
	17, // 27: woxqaq.v1.TaskService.GetTaskDetail:output_type -> woxqaq.v1.GetTaskDetailResponse
	23, // 28: woxqaq.v1.TaskService.ListTask:output_type -> woxqaq.v1.ListTaskResponse
	15, // 29: woxqaq.v1.TaskService.SubmitTask:output_type -> woxqaq.v1.SubmitTaskResponse
	19, // 30: woxqaq.v1.TaskService.Approve:output_type -> woxqaq.v1.ApproveResponse
	21, // 31: woxqaq.v1.TaskService.Reject:output_type -> woxqaq.v1.RejectResponse
	27, // [27:32] is the sub-list for method output_type
	22, // [22:27] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_v1_task_service_proto_init() }
func file_v1_task_service_proto_init() {
	if File_v1_task_service_proto != nil {
		return
	}
	file_v1_task_service_proto_msgTypes[4].OneofWrappers = []any{
		(*DataExportDetail_Ebs)(nil),
		(*DataExportDetail_Eatt)(nil),
	}
	file_v1_task_service_proto_msgTypes[8].OneofWrappers = []any{
		(*GetTaskDetailResponse_Ded)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_task_service_proto_rawDesc), len(file_v1_task_service_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_task_service_proto_goTypes,
		DependencyIndexes: file_v1_task_service_proto_depIdxs,
		EnumInfos:         file_v1_task_service_proto_enumTypes,
		MessageInfos:      file_v1_task_service_proto_msgTypes,
	}.Build()
	File_v1_task_service_proto = out.File
	file_v1_task_service_proto_goTypes = nil
	file_v1_task_service_proto_depIdxs = nil
}
