apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-strategy
  namespace: argo
data:
  step1: |
    {
      "triggers": [
        {
          "condition": "success",
          "channel": "slack",
          "recipients": "#approval-channel",
          "message": "Step 1 completed, awaiting approval."
        },
        {
          "condition": "timeout",
          "channel": "email",
          "recipients": "admin@example.com",
          "message": "Step 1 approval timed out!",
          "timeout": "1h"
        }
      ]
    }
  approval1: |
    {
      "triggers": [
        {
          "condition": "approved",
          "channel": "slack",
          "recipients": "#approval-channel",
          "message": "Approval 1 granted, proceeding to Step 2."
        },
        {
          "condition": "timeout",
          "channel": "email",
          "recipients": "admin@example.com",
          "message": "Approval 1 timed out!",
          "timeout": "1h"
        }
      ]
    }
  step2: |
    {
      "triggers": [
        {
          "condition": "success",
          "channel": "slack",
          "recipients": "#approval-channel",
          "message": "Step 2 completed successfully."
        }
      ]
    }